export type Locale =
  | "en" | "zh-TW" | "zh-CN"
  | "ja" | "ko" | "es" | "fr" | "de" | "pt"
  | "ar" | "ru" | "hi" | "it" | "nl" | "tr"
  | "vi" | "th" | "id" | "pl";

export const localeLabels: Record<Locale, string> = {
  en: "English", "zh-TW": "繁體中文", "zh-CN": "简体中文",
  ja: "日本語", ko: "한국어", es: "Español", fr: "Français",
  de: "Deutsch", pt: "Português", ar: "العربية", ru: "Русский",
  hi: "हिन्दी", it: "Italiano", nl: "Nederlands", tr: "Türkçe",
  vi: "Tiếng Việt", th: "ภาษาไทย", id: "Bahasa Indonesia", pl: "Polski",
};

export const translations = {
  en: {
    nav: { login: "Log in", getStarted: "Get started free", upload: "Upload", history: "History", signOut: "Sign out" },
    hero: { badge: "57 languages · AI dubbing · Subtitle burning", title1: "Translate your videos.", title2: "Effortlessly.", subtitle: "Upload a video, choose your languages, and get subtitles, dubbing, and burned-in captions — in minutes. Supports 57 languages.", ctaPrimary: "Start for free", ctaSecondary: "Sign in", freeNote: "Free: up to 2 min · No credit card required" },
    features: { title: "", items: [{ title: "57-language transcription", description: "Powered by Whisper AI — auto-detects language, handles accents, fast speech, and background noise." }, { title: "AI dubbing & subtitles", description: "Choose from 6 voices for dubbing, burn subtitles (source, target, or bilingual) directly into your video." }, { title: "Flexible output formats", description: "Download SRT files, burned-in subtitle video, or AI-dubbed MP4 — ready for any platform." }] },
    pricing: { title: "Simple pricing", subtitle: "Start free, upgrade when you need more.", free: { tier: "Free", price: "$0", features: ["Up to 2 min / video", "5 videos / month", "Bilingual SRT"] }, pro: { tier: "Pro", price: "Coming soon", features: ["Up to 20 min / video", "Unlimited videos", "Priority processing"] } },
    upload: { title: "New transcription", subtitle: "Upload a video to get subtitles.", dropTitle: "Drop your video here", dropSubtitle: "or click to browse · MP4, MOV, M4V", dropNote: "Free plan: up to 2 min", checking: "Checking", uploading: "Uploading…", queued: "Job queued — redirecting…", errorType: "Only MP4, MOV, or M4V files are supported.", errorDuration: (dur: number, max: number) => `Video is ${dur}s — free plan supports up to ${max}s (2 min).` },
    jobs: { title: "History", newVideo: "New video", empty: "No jobs yet", emptyLink: "Upload your first video →", loading: "Loading…", status: { pending: "pending", processing: "processing", completed: "completed", failed: "failed" } },
    jobDetail: { allJobs: "All jobs", loading: "Loading…", ready: "Your subtitle files are ready:", bilingual: "Bilingual SRT (EN + Chinese)", bilingualDesc: "Best for publishing — both languages stacked", englishOnly: "English SRT only", englishOnlyDesc: "Original transcription", pendingMsg: "Waiting in queue…", processingMsg: "Transcribing and translating…", pollingNote: "This page updates automatically", failedMsg: "Processing failed" },
    auth: { loginTitle: "Welcome back", loginSubtitle: "Sign in to your TranCut account", signupTitle: "Create your account", signupSubtitle: "Free — 5 videos / month, up to 2 min each", email: "Email", password: "Password", passwordHint: "Minimum 8 characters", signingIn: "Signing in…", signIn: "Sign in", creating: "Creating account…", createAccount: "Create account", noAccount: "No account?", signUpFree: "Sign up free", haveAccount: "Already have an account?" },
    footer: "TranCut · trancut.com",
  },

  "zh-TW": {
    nav: { login: "登入", getStarted: "免費開始使用", upload: "上傳", history: "歷史記錄", signOut: "登出" },
    hero: { badge: "57 種語言 · AI 配音 · 字幕烙印", title1: "翻譯你的影片，", title2: "輕鬆無比。", subtitle: "上傳影片，選擇語言，幾分鐘內取得字幕、AI 配音與烙印字幕影片。支援 57 種語言互譯。", ctaPrimary: "免費開始", ctaSecondary: "登入", freeNote: "免費版：最長 2 分鐘 · 無需信用卡" },
    features: { title: "", items: [{ title: "57 種語言轉錄", description: "採用 Whisper AI 自動偵測語言，能處理各種口音、語速與背景噪音。" }, { title: "AI 配音與字幕烙印", description: "6 種 AI 聲音配音，支援原文／譯文／雙語字幕直接烙印進影片。" }, { title: "彈性輸出格式", description: "下載 SRT 字幕檔、烙印字幕影片或 AI 配音 MP4，適用各大平台。" }] },
    pricing: { title: "簡單明瞭的定價", subtitle: "免費起步，需要更多時再升級。", free: { tier: "免費版", price: "$0", features: ["每部影片最長 2 分鐘", "每月 5 部影片", "雙語 SRT 字幕"] }, pro: { tier: "專業版", price: "即將推出", features: ["每部影片最長 20 分鐘", "無限制影片數量", "優先處理"] } },
    upload: { title: "新增轉錄任務", subtitle: "上傳影片以取得字幕。", dropTitle: "將影片拖曳至此", dropSubtitle: "或點擊瀏覽 · 支援 MP4、MOV、M4V", dropNote: "免費版：最長 2 分鐘", checking: "檢查中", uploading: "上傳中…", queued: "任務已排入佇列，正在跳轉…", errorType: "僅支援 MP4、MOV 或 M4V 格式。", errorDuration: (dur: number, max: number) => `影片長度為 ${dur} 秒，免費版上限為 ${max} 秒（2 分鐘）。` },
    jobs: { title: "歷史記錄", newVideo: "新影片", empty: "尚無任務", emptyLink: "上傳你的第一部影片 →", loading: "載入中…", status: { pending: "等待中", processing: "處理中", completed: "已完成", failed: "失敗" } },
    jobDetail: { allJobs: "所有任務", loading: "載入中…", ready: "字幕檔案已準備就緒：", bilingual: "雙語 SRT（英文 + 中文）", bilingualDesc: "適合發布使用，雙語交疊顯示", englishOnly: "純英文 SRT", englishOnlyDesc: "原始轉錄內容", pendingMsg: "等待佇列中…", processingMsg: "正在轉錄與翻譯…", pollingNote: "本頁面會自動更新", failedMsg: "處理失敗" },
    auth: { loginTitle: "歡迎回來", loginSubtitle: "登入你的 TranCut 帳號", signupTitle: "建立帳號", signupSubtitle: "免費版：每月 5 部影片，每部最長 2 分鐘", email: "電子郵件", password: "密碼", passwordHint: "最少 8 個字元", signingIn: "登入中…", signIn: "登入", creating: "建立帳號中…", createAccount: "建立帳號", noAccount: "還沒有帳號？", signUpFree: "免費註冊", haveAccount: "已有帳號？" },
    footer: "TranCut · trancut.com",
  },

  "zh-CN": {
    nav: { login: "登录", getStarted: "免费开始使用", upload: "上传", history: "历史记录", signOut: "退出登录" },
    hero: { badge: "57 种语言 · AI 配音 · 字幕烙印", title1: "翻译你的视频，", title2: "轻松无比。", subtitle: "上传视频，选择语言，几分钟内获得字幕、AI 配音与烙印字幕视频。支持 57 种语言互译。", ctaPrimary: "免费开始", ctaSecondary: "登录", freeNote: "免费版：最长 2 分钟 · 无需信用卡" },
    features: { title: "", items: [{ title: "57 种语言转录", description: "采用 Whisper AI 自动检测语言，能处理各种口音、语速与背景噪音。" }, { title: "AI 配音与字幕烙印", description: "6 种 AI 声音配音，支持原文／译文／双语字幕直接烙印进视频。" }, { title: "灵活输出格式", description: "下载 SRT 字幕文件、烙印字幕视频或 AI 配音 MP4，适用各大平台。" }] },
    pricing: { title: "简单明了的定价", subtitle: "免费起步，需要更多时再升级。", free: { tier: "免费版", price: "$0", features: ["每个视频最长 2 分钟", "每月 5 个视频", "双语 SRT 字幕"] }, pro: { tier: "专业版", price: "即将推出", features: ["每个视频最长 20 分钟", "无限视频数量", "优先处理"] } },
    upload: { title: "新建转录任务", subtitle: "上传视频以获取字幕。", dropTitle: "将视频拖拽至此", dropSubtitle: "或点击浏览 · 支持 MP4、MOV、M4V", dropNote: "免费版：最长 2 分钟", checking: "检查中", uploading: "上传中…", queued: "任务已加入队列，正在跳转…", errorType: "仅支持 MP4、MOV 或 M4V 格式。", errorDuration: (dur: number, max: number) => `视频时长为 ${dur} 秒，免费版上限为 ${max} 秒（2 分钟）。` },
    jobs: { title: "历史记录", newVideo: "新视频", empty: "暂无任务", emptyLink: "上传你的第一个视频 →", loading: "加载中…", status: { pending: "等待中", processing: "处理中", completed: "已完成", failed: "失败" } },
    jobDetail: { allJobs: "所有任务", loading: "加载中…", ready: "字幕文件已准备就绪：", bilingual: "双语 SRT（英文 + 中文）", bilingualDesc: "适合发布使用，双语叠加显示", englishOnly: "纯英文 SRT", englishOnlyDesc: "原始转录内容", pendingMsg: "等待队列中…", processingMsg: "正在转录与翻译…", pollingNote: "本页面会自动更新", failedMsg: "处理失败" },
    auth: { loginTitle: "欢迎回来", loginSubtitle: "登录你的 TranCut 账号", signupTitle: "创建账号", signupSubtitle: "免费版：每月 5 个视频，每个最长 2 分钟", email: "电子邮件", password: "密码", passwordHint: "最少 8 个字符", signingIn: "登录中…", signIn: "登录", creating: "创建账号中…", createAccount: "创建账号", noAccount: "还没有账号？", signUpFree: "免费注册", haveAccount: "已有账号？" },
    footer: "TranCut · trancut.com",
  },

  ja: {
    nav: { login: "ログイン", getStarted: "無料で始める", upload: "アップロード", history: "履歴", signOut: "サインアウト" },
    hero: { badge: "57言語 · AI吹替 · 字幕焼き込み", title1: "動画を翻訳。", title2: "手軽に。", subtitle: "動画をアップロードし、言語を選択するだけで、字幕・AI吹替・焼き込み字幕が数分で完成。57言語対応。", ctaPrimary: "無料で始める", ctaSecondary: "サインイン", freeNote: "無料プラン：最大2分 · クレジットカード不要" },
    features: { title: "", items: [{ title: "57言語の文字起こし", description: "Whisper AIで言語を自動検出。アクセント・早口・ノイズにも対応。" }, { title: "AI吹替と字幕", description: "6種類の声で吹替、字幕（原文・訳文・バイリンガル）を動画に焼き込み。" }, { title: "柔軟な出力形式", description: "SRTファイル、字幕焼き込み動画、AI吹替MP4をダウンロード。各プラットフォーム対応。" }] },
    pricing: { title: "シンプルな料金体系", subtitle: "無料から始めて、必要に応じてアップグレード。", free: { tier: "無料", price: "$0", features: ["最大2分 / 動画", "5動画 / 月", "バイリンガルSRT"] }, pro: { tier: "プロ", price: "近日公開", features: ["最大20分 / 動画", "無制限", "優先処理"] } },
    upload: { title: "新しい文字起こし", subtitle: "動画をアップロードして字幕を取得。", dropTitle: "ここに動画をドロップ", dropSubtitle: "またはクリックして参照 · MP4、MOV、M4V", dropNote: "無料プラン：最大2分", checking: "確認中", uploading: "アップロード中…", queued: "ジョブをキューに追加 — リダイレクト中…", errorType: "MP4、MOV、M4Vファイルのみ対応しています。", errorDuration: (dur: number, max: number) => `動画は${dur}秒です。無料プランは最大${max}秒（2分）まで。` },
    jobs: { title: "履歴", newVideo: "新しい動画", empty: "ジョブはありません", emptyLink: "最初の動画をアップロード →", loading: "読み込み中…", status: { pending: "待機中", processing: "処理中", completed: "完了", failed: "失敗" } },
    jobDetail: { allJobs: "すべてのジョブ", loading: "読み込み中…", ready: "字幕ファイルの準備ができました：", bilingual: "バイリンガルSRT", bilingualDesc: "公開に最適 — 両言語を重ねて表示", englishOnly: "英語SRTのみ", englishOnlyDesc: "オリジナルの文字起こし", pendingMsg: "キューで待機中…", processingMsg: "文字起こしと翻訳中…", pollingNote: "このページは自動更新されます", failedMsg: "処理に失敗しました" },
    auth: { loginTitle: "おかえりなさい", loginSubtitle: "TranCutアカウントにサインイン", signupTitle: "アカウントを作成", signupSubtitle: "無料 — 月5本、最大2分まで", email: "メールアドレス", password: "パスワード", passwordHint: "8文字以上", signingIn: "サインイン中…", signIn: "サインイン", creating: "アカウント作成中…", createAccount: "アカウントを作成", noAccount: "アカウントをお持ちでない方は？", signUpFree: "無料で登録", haveAccount: "すでにアカウントをお持ちですか？" },
    footer: "TranCut · trancut.com",
  },

  ko: {
    nav: { login: "로그인", getStarted: "무료로 시작하기", upload: "업로드", history: "기록", signOut: "로그아웃" },
    hero: { badge: "57개 언어 · AI 더빙 · 자막 삽입", title1: "동영상을 번역하세요.", title2: "손쉽게.", subtitle: "동영상을 업로드하고 언어를 선택하면 몇 분 안에 자막, AI 더빙, 삽입 자막을 받을 수 있습니다. 57개 언어 지원.", ctaPrimary: "무료로 시작", ctaSecondary: "로그인", freeNote: "무료: 최대 2분 · 신용카드 불필요" },
    features: { title: "", items: [{ title: "57개 언어 전사", description: "Whisper AI로 언어를 자동 감지. 억양, 빠른 말, 배경 소음 처리." }, { title: "AI 더빙 및 자막", description: "6가지 AI 음성으로 더빙, 자막(원문/번역/이중 언어)을 동영상에 직접 삽입." }, { title: "유연한 출력 형식", description: "SRT 파일, 자막 삽입 동영상, AI 더빙 MP4 다운로드. 모든 플랫폼 지원." }] },
    pricing: { title: "간단한 요금제", subtitle: "무료로 시작, 필요할 때 업그레이드.", free: { tier: "무료", price: "$0", features: ["최대 2분 / 동영상", "5개 동영상 / 월", "이중 언어 SRT"] }, pro: { tier: "프로", price: "출시 예정", features: ["최대 20분 / 동영상", "무제한 동영상", "우선 처리"] } },
    upload: { title: "새 전사", subtitle: "동영상을 업로드하여 자막을 받으세요.", dropTitle: "여기에 동영상을 드롭하세요", dropSubtitle: "또는 클릭하여 찾아보기 · MP4, MOV, M4V", dropNote: "무료 플랜: 최대 2분", checking: "확인 중", uploading: "업로드 중…", queued: "작업이 대기열에 추가됨 — 리디렉션 중…", errorType: "MP4, MOV 또는 M4V 파일만 지원됩니다.", errorDuration: (dur: number, max: number) => `동영상이 ${dur}초입니다 — 무료 플랜은 최대 ${max}초(2분)까지 지원합니다.` },
    jobs: { title: "기록", newVideo: "새 동영상", empty: "작업 없음", emptyLink: "첫 번째 동영상 업로드 →", loading: "로딩 중…", status: { pending: "대기 중", processing: "처리 중", completed: "완료", failed: "실패" } },
    jobDetail: { allJobs: "모든 작업", loading: "로딩 중…", ready: "자막 파일이 준비되었습니다:", bilingual: "이중 언어 SRT", bilingualDesc: "게시에 최적 — 두 언어 중첩 표시", englishOnly: "영어 SRT만", englishOnlyDesc: "원본 전사", pendingMsg: "대기열에서 기다리는 중…", processingMsg: "전사 및 번역 중…", pollingNote: "이 페이지는 자동으로 업데이트됩니다", failedMsg: "처리 실패" },
    auth: { loginTitle: "돌아오신 것을 환영합니다", loginSubtitle: "TranCut 계정에 로그인", signupTitle: "계정 만들기", signupSubtitle: "무료 — 월 5개 동영상, 최대 2분", email: "이메일", password: "비밀번호", passwordHint: "최소 8자", signingIn: "로그인 중…", signIn: "로그인", creating: "계정 생성 중…", createAccount: "계정 만들기", noAccount: "계정이 없으신가요?", signUpFree: "무료 가입", haveAccount: "이미 계정이 있으신가요?" },
    footer: "TranCut · trancut.com",
  },

  es: {
    nav: { login: "Iniciar sesión", getStarted: "Empezar gratis", upload: "Subir", history: "Historial", signOut: "Cerrar sesión" },
    hero: { badge: "57 idiomas · Doblaje con IA · Subtítulos integrados", title1: "Traduce tus vídeos.", title2: "Sin esfuerzo.", subtitle: "Sube un vídeo, elige los idiomas y obtén subtítulos, doblaje y subtítulos integrados en minutos. Compatible con 57 idiomas.", ctaPrimary: "Empezar gratis", ctaSecondary: "Iniciar sesión", freeNote: "Gratis: hasta 2 min · Sin tarjeta de crédito" },
    features: { title: "", items: [{ title: "Transcripción en 57 idiomas", description: "Powered by Whisper AI — detecta idioma automáticamente, maneja acentos, habla rápida y ruido de fondo." }, { title: "Doblaje y subtítulos con IA", description: "Elige entre 6 voces para doblaje, quema subtítulos (original, traducción o bilingüe) directamente en tu vídeo." }, { title: "Formatos de salida flexibles", description: "Descarga archivos SRT, vídeo con subtítulos integrados o MP4 doblado con IA — listo para cualquier plataforma." }] },
    pricing: { title: "Precios simples", subtitle: "Comienza gratis, actualiza cuando necesites más.", free: { tier: "Gratis", price: "$0", features: ["Hasta 2 min / vídeo", "5 vídeos / mes", "SRT bilingüe"] }, pro: { tier: "Pro", price: "Próximamente", features: ["Hasta 20 min / vídeo", "Vídeos ilimitados", "Procesamiento prioritario"] } },
    upload: { title: "Nueva transcripción", subtitle: "Sube un vídeo para obtener subtítulos.", dropTitle: "Arrastra tu vídeo aquí", dropSubtitle: "o haz clic para buscar · MP4, MOV, M4V", dropNote: "Plan gratuito: hasta 2 min", checking: "Verificando", uploading: "Subiendo…", queued: "Trabajo en cola — redirigiendo…", errorType: "Solo se admiten archivos MP4, MOV o M4V.", errorDuration: (dur: number, max: number) => `El vídeo dura ${dur}s — el plan gratuito admite hasta ${max}s (2 min).` },
    jobs: { title: "Historial", newVideo: "Nuevo vídeo", empty: "Sin trabajos", emptyLink: "Sube tu primer vídeo →", loading: "Cargando…", status: { pending: "pendiente", processing: "procesando", completed: "completado", failed: "fallido" } },
    jobDetail: { allJobs: "Todos los trabajos", loading: "Cargando…", ready: "Tus archivos de subtítulos están listos:", bilingual: "SRT bilingüe", bilingualDesc: "Ideal para publicar — ambos idiomas apilados", englishOnly: "Solo SRT en inglés", englishOnlyDesc: "Transcripción original", pendingMsg: "Esperando en la cola…", processingMsg: "Transcribiendo y traduciendo…", pollingNote: "Esta página se actualiza automáticamente", failedMsg: "Error en el procesamiento" },
    auth: { loginTitle: "Bienvenido de nuevo", loginSubtitle: "Inicia sesión en tu cuenta de TranCut", signupTitle: "Crea tu cuenta", signupSubtitle: "Gratis — 5 vídeos al mes, hasta 2 min cada uno", email: "Correo electrónico", password: "Contraseña", passwordHint: "Mínimo 8 caracteres", signingIn: "Iniciando sesión…", signIn: "Iniciar sesión", creating: "Creando cuenta…", createAccount: "Crear cuenta", noAccount: "¿Sin cuenta?", signUpFree: "Regístrate gratis", haveAccount: "¿Ya tienes una cuenta?" },
    footer: "TranCut · trancut.com",
  },

  fr: {
    nav: { login: "Connexion", getStarted: "Commencer gratuitement", upload: "Télécharger", history: "Historique", signOut: "Se déconnecter" },
    hero: { badge: "57 langues · Doublage IA · Sous-titres incrustés", title1: "Traduisez vos vidéos.", title2: "Sans effort.", subtitle: "Téléchargez une vidéo, choisissez vos langues et obtenez des sous-titres, un doublage et des sous-titres incrustés en quelques minutes. Prend en charge 57 langues.", ctaPrimary: "Commencer gratuitement", ctaSecondary: "Connexion", freeNote: "Gratuit : jusqu'à 2 min · Sans carte de crédit" },
    features: { title: "", items: [{ title: "Transcription en 57 langues", description: "Propulsé par Whisper AI — détecte automatiquement la langue, gère les accents, la parole rapide et le bruit de fond." }, { title: "Doublage et sous-titres IA", description: "Choisissez parmi 6 voix pour le doublage, incrustez des sous-titres (source, cible ou bilingues) directement dans votre vidéo." }, { title: "Formats de sortie flexibles", description: "Téléchargez des fichiers SRT, une vidéo avec sous-titres incrustés ou un MP4 doublé par IA — prêt pour toutes les plateformes." }] },
    pricing: { title: "Tarifs simples", subtitle: "Commencez gratuitement, mettez à niveau quand vous en avez besoin.", free: { tier: "Gratuit", price: "$0", features: ["Jusqu'à 2 min / vidéo", "5 vidéos / mois", "SRT bilingue"] }, pro: { tier: "Pro", price: "Bientôt disponible", features: ["Jusqu'à 20 min / vidéo", "Vidéos illimitées", "Traitement prioritaire"] } },
    upload: { title: "Nouvelle transcription", subtitle: "Téléchargez une vidéo pour obtenir des sous-titres.", dropTitle: "Déposez votre vidéo ici", dropSubtitle: "ou cliquez pour parcourir · MP4, MOV, M4V", dropNote: "Plan gratuit : jusqu'à 2 min", checking: "Vérification", uploading: "Téléchargement…", queued: "Tâche en file d'attente — redirection…", errorType: "Seuls les fichiers MP4, MOV ou M4V sont pris en charge.", errorDuration: (dur: number, max: number) => `La vidéo dure ${dur}s — le plan gratuit prend en charge jusqu'à ${max}s (2 min).` },
    jobs: { title: "Historique", newVideo: "Nouvelle vidéo", empty: "Aucune tâche", emptyLink: "Téléchargez votre première vidéo →", loading: "Chargement…", status: { pending: "en attente", processing: "en traitement", completed: "terminé", failed: "échoué" } },
    jobDetail: { allJobs: "Toutes les tâches", loading: "Chargement…", ready: "Vos fichiers de sous-titres sont prêts :", bilingual: "SRT bilingue", bilingualDesc: "Idéal pour la publication — les deux langues empilées", englishOnly: "SRT anglais uniquement", englishOnlyDesc: "Transcription originale", pendingMsg: "En attente dans la file…", processingMsg: "Transcription et traduction…", pollingNote: "Cette page se met à jour automatiquement", failedMsg: "Échec du traitement" },
    auth: { loginTitle: "Bon retour", loginSubtitle: "Connectez-vous à votre compte TranCut", signupTitle: "Créez votre compte", signupSubtitle: "Gratuit — 5 vidéos / mois, jusqu'à 2 min chacune", email: "Adresse e-mail", password: "Mot de passe", passwordHint: "Minimum 8 caractères", signingIn: "Connexion…", signIn: "Se connecter", creating: "Création du compte…", createAccount: "Créer un compte", noAccount: "Pas de compte ?", signUpFree: "S'inscrire gratuitement", haveAccount: "Vous avez déjà un compte ?" },
    footer: "TranCut · trancut.com",
  },

  de: {
    nav: { login: "Anmelden", getStarted: "Kostenlos starten", upload: "Hochladen", history: "Verlauf", signOut: "Abmelden" },
    hero: { badge: "57 Sprachen · KI-Synchronisation · Eingebrannte Untertitel", title1: "Übersetze deine Videos.", title2: "Mühelos.", subtitle: "Lade ein Video hoch, wähle deine Sprachen und erhalte in Minuten Untertitel, Synchronisation und eingebrannte Untertitel. Unterstützt 57 Sprachen.", ctaPrimary: "Kostenlos starten", ctaSecondary: "Anmelden", freeNote: "Kostenlos: bis zu 2 Min · Keine Kreditkarte erforderlich" },
    features: { title: "", items: [{ title: "Transkription in 57 Sprachen", description: "Powered by Whisper AI — erkennt Sprache automatisch, verarbeitet Akzente, schnelle Sprache und Hintergrundgeräusche." }, { title: "KI-Synchronisation und Untertitel", description: "Wähle aus 6 Stimmen für die Synchronisation, brenne Untertitel (Quelle, Ziel oder zweisprachig) direkt in dein Video." }, { title: "Flexible Ausgabeformate", description: "Lade SRT-Dateien, Videos mit eingebrannten Untertiteln oder KI-synchronisierte MP4s herunter — für jede Plattform bereit." }] },
    pricing: { title: "Einfache Preise", subtitle: "Starte kostenlos, upgrade wenn du mehr brauchst.", free: { tier: "Kostenlos", price: "$0", features: ["Bis zu 2 Min / Video", "5 Videos / Monat", "Zweisprachige SRT"] }, pro: { tier: "Pro", price: "Demnächst", features: ["Bis zu 20 Min / Video", "Unbegrenzte Videos", "Priorisierte Verarbeitung"] } },
    upload: { title: "Neue Transkription", subtitle: "Lade ein Video hoch, um Untertitel zu erhalten.", dropTitle: "Video hier ablegen", dropSubtitle: "oder klicken zum Durchsuchen · MP4, MOV, M4V", dropNote: "Kostenloser Plan: bis zu 2 Min", checking: "Überprüfung", uploading: "Hochladen…", queued: "Job in der Warteschlange — Weiterleitung…", errorType: "Nur MP4-, MOV- oder M4V-Dateien werden unterstützt.", errorDuration: (dur: number, max: number) => `Video ist ${dur}s lang — kostenloser Plan unterstützt bis zu ${max}s (2 Min).` },
    jobs: { title: "Verlauf", newVideo: "Neues Video", empty: "Keine Jobs", emptyLink: "Lade dein erstes Video hoch →", loading: "Laden…", status: { pending: "ausstehend", processing: "wird verarbeitet", completed: "abgeschlossen", failed: "fehlgeschlagen" } },
    jobDetail: { allJobs: "Alle Jobs", loading: "Laden…", ready: "Deine Untertiteldateien sind bereit:", bilingual: "Zweisprachige SRT", bilingualDesc: "Ideal zum Veröffentlichen — beide Sprachen gestapelt", englishOnly: "Nur englische SRT", englishOnlyDesc: "Originaltranskription", pendingMsg: "Warte in der Warteschlange…", processingMsg: "Transkribiere und übersetze…", pollingNote: "Diese Seite aktualisiert sich automatisch", failedMsg: "Verarbeitung fehlgeschlagen" },
    auth: { loginTitle: "Willkommen zurück", loginSubtitle: "Melde dich bei deinem TranCut-Konto an", signupTitle: "Konto erstellen", signupSubtitle: "Kostenlos — 5 Videos/Monat, bis zu 2 Min jeweils", email: "E-Mail", password: "Passwort", passwordHint: "Mindestens 8 Zeichen", signingIn: "Anmelden…", signIn: "Anmelden", creating: "Konto erstellen…", createAccount: "Konto erstellen", noAccount: "Kein Konto?", signUpFree: "Kostenlos registrieren", haveAccount: "Bereits ein Konto?" },
    footer: "TranCut · trancut.com",
  },

  pt: {
    nav: { login: "Entrar", getStarted: "Começar gratuitamente", upload: "Enviar", history: "Histórico", signOut: "Sair" },
    hero: { badge: "57 idiomas · Dublagem com IA · Legendas incorporadas", title1: "Traduza seus vídeos.", title2: "Sem esforço.", subtitle: "Faça upload de um vídeo, escolha os idiomas e obtenha legendas, dublagem e legendas incorporadas em minutos. Suporta 57 idiomas.", ctaPrimary: "Começar gratuitamente", ctaSecondary: "Entrar", freeNote: "Grátis: até 2 min · Sem cartão de crédito" },
    features: { title: "", items: [{ title: "Transcrição em 57 idiomas", description: "Powered by Whisper AI — detecta idioma automaticamente, lida com sotaques, fala rápida e ruído de fundo." }, { title: "Dublagem e legendas com IA", description: "Escolha entre 6 vozes para dublagem, grave legendas (original, tradução ou bilíngue) diretamente no seu vídeo." }, { title: "Formatos de saída flexíveis", description: "Baixe arquivos SRT, vídeo com legendas incorporadas ou MP4 dublado com IA — pronto para qualquer plataforma." }] },
    pricing: { title: "Preços simples", subtitle: "Comece gratuitamente, atualize quando precisar de mais.", free: { tier: "Grátis", price: "$0", features: ["Até 2 min / vídeo", "5 vídeos / mês", "SRT bilíngue"] }, pro: { tier: "Pro", price: "Em breve", features: ["Até 20 min / vídeo", "Vídeos ilimitados", "Processamento prioritário"] } },
    upload: { title: "Nova transcrição", subtitle: "Faça upload de um vídeo para obter legendas.", dropTitle: "Solte seu vídeo aqui", dropSubtitle: "ou clique para navegar · MP4, MOV, M4V", dropNote: "Plano gratuito: até 2 min", checking: "Verificando", uploading: "Enviando…", queued: "Trabalho na fila — redirecionando…", errorType: "Apenas arquivos MP4, MOV ou M4V são suportados.", errorDuration: (dur: number, max: number) => `O vídeo tem ${dur}s — o plano gratuito suporta até ${max}s (2 min).` },
    jobs: { title: "Histórico", newVideo: "Novo vídeo", empty: "Sem trabalhos", emptyLink: "Faça upload do seu primeiro vídeo →", loading: "Carregando…", status: { pending: "pendente", processing: "processando", completed: "concluído", failed: "falhou" } },
    jobDetail: { allJobs: "Todos os trabalhos", loading: "Carregando…", ready: "Seus arquivos de legendas estão prontos:", bilingual: "SRT bilíngue", bilingualDesc: "Ideal para publicar — ambos os idiomas empilhados", englishOnly: "Apenas SRT em inglês", englishOnlyDesc: "Transcrição original", pendingMsg: "Aguardando na fila…", processingMsg: "Transcrevendo e traduzindo…", pollingNote: "Esta página é atualizada automaticamente", failedMsg: "Falha no processamento" },
    auth: { loginTitle: "Bem-vindo de volta", loginSubtitle: "Entre na sua conta TranCut", signupTitle: "Crie sua conta", signupSubtitle: "Grátis — 5 vídeos/mês, até 2 min cada", email: "E-mail", password: "Senha", passwordHint: "Mínimo 8 caracteres", signingIn: "Entrando…", signIn: "Entrar", creating: "Criando conta…", createAccount: "Criar conta", noAccount: "Sem conta?", signUpFree: "Registre-se gratuitamente", haveAccount: "Já tem uma conta?" },
    footer: "TranCut · trancut.com",
  },

  ar: {
    nav: { login: "تسجيل الدخول", getStarted: "ابدأ مجاناً", upload: "رفع", history: "السجل", signOut: "تسجيل الخروج" },
    hero: { badge: "٥٧ لغة · دبلجة بالذكاء الاصطناعي · دمج الترجمة", title1: "ترجم مقاطع الفيديو الخاصة بك.", title2: "بكل سهولة.", subtitle: "ارفع مقطع فيديو، اختر اللغات، واحصل على الترجمة والدبلجة والترجمة المضمّنة في دقائق. يدعم ٥٧ لغة.", ctaPrimary: "ابدأ مجاناً", ctaSecondary: "تسجيل الدخول", freeNote: "مجاناً: حتى دقيقتين · لا حاجة لبطاقة ائتمانية" },
    features: { title: "", items: [{ title: "النسخ بـ٥٧ لغة", description: "مدعوم بـ Whisper AI — يكتشف اللغة تلقائياً، ويتعامل مع اللهجات والكلام السريع وضوضاء الخلفية." }, { title: "الدبلجة والترجمة بالذكاء الاصطناعي", description: "اختر من بين ٦ أصوات للدبلجة، وادمج الترجمة (أصلية أو مترجمة أو ثنائية اللغة) مباشرة في فيديوك." }, { title: "تنسيقات إخراج مرنة", description: "نزّل ملفات SRT أو فيديو مع ترجمة مضمّنة أو MP4 مدبلج بالذكاء الاصطناعي — جاهز لأي منصة." }] },
    pricing: { title: "تسعير بسيط", subtitle: "ابدأ مجاناً، وقم بالترقية عند الحاجة.", free: { tier: "مجاني", price: "$0", features: ["حتى دقيقتين / فيديو", "٥ فيديوهات / شهر", "SRT ثنائي اللغة"] }, pro: { tier: "احترافي", price: "قريباً", features: ["حتى ٢٠ دقيقة / فيديو", "فيديوهات غير محدودة", "معالجة ذات أولوية"] } },
    upload: { title: "نسخ جديد", subtitle: "ارفع مقطع فيديو للحصول على الترجمة.", dropTitle: "اسحب مقطع الفيديو هنا", dropSubtitle: "أو انقر للتصفح · MP4 أو MOV أو M4V", dropNote: "الخطة المجانية: حتى دقيقتين", checking: "جاري التحقق", uploading: "جاري الرفع…", queued: "تمت إضافة المهمة للقائمة — جاري التحويل…", errorType: "يُدعم فقط ملفات MP4 أو MOV أو M4V.", errorDuration: (dur: number, max: number) => `مدة الفيديو ${dur}ث — الخطة المجانية تدعم حتى ${max}ث (دقيقتان).` },
    jobs: { title: "السجل", newVideo: "فيديو جديد", empty: "لا توجد مهام", emptyLink: "ارفع أول فيديو لك ←", loading: "جاري التحميل…", status: { pending: "في الانتظار", processing: "قيد المعالجة", completed: "مكتمل", failed: "فشل" } },
    jobDetail: { allJobs: "جميع المهام", loading: "جاري التحميل…", ready: "ملفات الترجمة جاهزة:", bilingual: "SRT ثنائي اللغة", bilingualDesc: "الأفضل للنشر — كلتا اللغتين مكدستان", englishOnly: "SRT بالإنجليزية فقط", englishOnlyDesc: "النسخ الأصلي", pendingMsg: "في انتظار الدور…", processingMsg: "جاري النسخ والترجمة…", pollingNote: "تتحدث هذه الصفحة تلقائياً", failedMsg: "فشلت المعالجة" },
    auth: { loginTitle: "مرحباً بعودتك", loginSubtitle: "سجّل الدخول إلى حساب TranCut", signupTitle: "أنشئ حسابك", signupSubtitle: "مجاناً — ٥ فيديوهات شهرياً، حتى دقيقتين لكل منها", email: "البريد الإلكتروني", password: "كلمة المرور", passwordHint: "٨ أحرف على الأقل", signingIn: "جاري تسجيل الدخول…", signIn: "تسجيل الدخول", creating: "جاري إنشاء الحساب…", createAccount: "إنشاء حساب", noAccount: "ليس لديك حساب؟", signUpFree: "التسجيل مجاناً", haveAccount: "لديك حساب بالفعل؟" },
    footer: "TranCut · trancut.com",
  },

  ru: {
    nav: { login: "Войти", getStarted: "Начать бесплатно", upload: "Загрузить", history: "История", signOut: "Выйти" },
    hero: { badge: "57 языков · ИИ-дубляж · Встроенные субтитры", title1: "Переводите свои видео.", title2: "Без усилий.", subtitle: "Загрузите видео, выберите языки и получите субтитры, дубляж и встроенные субтитры за несколько минут. Поддерживает 57 языков.", ctaPrimary: "Начать бесплатно", ctaSecondary: "Войти", freeNote: "Бесплатно: до 2 мин · Без кредитной карты" },
    features: { title: "", items: [{ title: "Транскрипция на 57 языках", description: "Работает на Whisper AI — автоматически определяет язык, обрабатывает акценты, быструю речь и фоновый шум." }, { title: "ИИ-дубляж и субтитры", description: "Выберите из 6 голосов для дубляжа, встройте субтитры (исходные, переведённые или двуязычные) прямо в видео." }, { title: "Гибкие форматы вывода", description: "Скачивайте SRT-файлы, видео со встроенными субтитрами или MP4 с ИИ-дубляжом — готово для любой платформы." }] },
    pricing: { title: "Простые цены", subtitle: "Начните бесплатно, обновитесь когда нужно больше.", free: { tier: "Бесплатно", price: "$0", features: ["До 2 мин / видео", "5 видео / месяц", "Двуязычный SRT"] }, pro: { tier: "Про", price: "Скоро", features: ["До 20 мин / видео", "Неограниченно видео", "Приоритетная обработка"] } },
    upload: { title: "Новая транскрипция", subtitle: "Загрузите видео для получения субтитров.", dropTitle: "Перетащите видео сюда", dropSubtitle: "или нажмите для поиска · MP4, MOV, M4V", dropNote: "Бесплатный план: до 2 мин", checking: "Проверка", uploading: "Загрузка…", queued: "Задание в очереди — перенаправление…", errorType: "Поддерживаются только файлы MP4, MOV или M4V.", errorDuration: (dur: number, max: number) => `Видео длится ${dur}с — бесплатный план поддерживает до ${max}с (2 мин).` },
    jobs: { title: "История", newVideo: "Новое видео", empty: "Нет заданий", emptyLink: "Загрузите своё первое видео →", loading: "Загрузка…", status: { pending: "ожидание", processing: "обработка", completed: "завершено", failed: "ошибка" } },
    jobDetail: { allJobs: "Все задания", loading: "Загрузка…", ready: "Ваши файлы субтитров готовы:", bilingual: "Двуязычный SRT", bilingualDesc: "Лучший для публикации — оба языка наложены", englishOnly: "Только английский SRT", englishOnlyDesc: "Оригинальная транскрипция", pendingMsg: "Ожидание в очереди…", processingMsg: "Транскрипция и перевод…", pollingNote: "Эта страница обновляется автоматически", failedMsg: "Ошибка обработки" },
    auth: { loginTitle: "С возвращением", loginSubtitle: "Войдите в свою учётную запись TranCut", signupTitle: "Создайте аккаунт", signupSubtitle: "Бесплатно — 5 видео/месяц, до 2 мин каждое", email: "Электронная почта", password: "Пароль", passwordHint: "Минимум 8 символов", signingIn: "Вход…", signIn: "Войти", creating: "Создание аккаунта…", createAccount: "Создать аккаунт", noAccount: "Нет аккаунта?", signUpFree: "Зарегистрироваться бесплатно", haveAccount: "Уже есть аккаунт?" },
    footer: "TranCut · trancut.com",
  },

  hi: {
    nav: { login: "लॉग इन", getStarted: "मुफ़्त शुरू करें", upload: "अपलोड", history: "इतिहास", signOut: "साइन आउट" },
    hero: { badge: "57 भाषाएं · AI डबिंग · सबटाइटल एम्बेड", title1: "अपने वीडियो अनुवाद करें।", title2: "आसानी से।", subtitle: "वीडियो अपलोड करें, भाषाएं चुनें, और मिनटों में सबटाइटल, डबिंग और एम्बेडेड कैप्शन पाएं। 57 भाषाओं में समर्थन।", ctaPrimary: "मुफ़्त शुरू करें", ctaSecondary: "साइन इन", freeNote: "मुफ़्त: 2 मिनट तक · क्रेडिट कार्ड की आवश्यकता नहीं" },
    features: { title: "", items: [{ title: "57 भाषाओं में ट्रांसक्रिप्शन", description: "Whisper AI द्वारा संचालित — भाषा स्वचालित रूप से पहचानती है, उच्चारण, तेज़ बोली और पृष्ठभूमि शोर संभालती है।" }, { title: "AI डबिंग और सबटाइटल", description: "डबिंग के लिए 6 आवाज़ों में से चुनें, सबटाइटल (स्रोत, लक्ष्य या द्विभाषी) सीधे वीडियो में एम्बेड करें।" }, { title: "लचीले आउटपुट फॉर्मेट", description: "SRT फ़ाइलें, एम्बेडेड सबटाइटल वाला वीडियो, या AI-डब्ड MP4 डाउनलोड करें — किसी भी प्लेटफ़ॉर्म के लिए तैयार।" }] },
    pricing: { title: "सरल मूल्य निर्धारण", subtitle: "मुफ़्त शुरू करें, ज़रूरत पड़ने पर अपग्रेड करें।", free: { tier: "मुफ़्त", price: "$0", features: ["2 मिनट तक / वीडियो", "5 वीडियो / माह", "द्विभाषी SRT"] }, pro: { tier: "प्रो", price: "जल्द आ रहा है", features: ["20 मिनट तक / वीडियो", "असीमित वीडियो", "प्राथमिकता प्रसंस्करण"] } },
    upload: { title: "नया ट्रांसक्रिप्शन", subtitle: "सबटाइटल पाने के लिए वीडियो अपलोड करें।", dropTitle: "यहां वीडियो ड्रॉप करें", dropSubtitle: "या ब्राउज़ करने के लिए क्लिक करें · MP4, MOV, M4V", dropNote: "मुफ़्त प्लान: 2 मिनट तक", checking: "जांच हो रही है", uploading: "अपलोड हो रहा है…", queued: "कार्य कतार में है — रीडायरेक्ट हो रहा है…", errorType: "केवल MP4, MOV या M4V फ़ाइलें समर्थित हैं।", errorDuration: (dur: number, max: number) => `वीडियो ${dur}s का है — मुफ़्त प्लान ${max}s (2 मिनट) तक समर्थन करता है।` },
    jobs: { title: "इतिहास", newVideo: "नया वीडियो", empty: "कोई कार्य नहीं", emptyLink: "अपना पहला वीडियो अपलोड करें →", loading: "लोड हो रहा है…", status: { pending: "लंबित", processing: "प्रसंस्करण", completed: "पूर्ण", failed: "विफल" } },
    jobDetail: { allJobs: "सभी कार्य", loading: "लोड हो रहा है…", ready: "आपकी सबटाइटल फ़ाइलें तैयार हैं:", bilingual: "द्विभाषी SRT", bilingualDesc: "प्रकाशन के लिए सर्वश्रेष्ठ — दोनों भाषाएं एक साथ", englishOnly: "केवल अंग्रेज़ी SRT", englishOnlyDesc: "मूल ट्रांसक्रिप्शन", pendingMsg: "कतार में प्रतीक्षा…", processingMsg: "ट्रांसक्राइब और अनुवाद हो रहा है…", pollingNote: "यह पेज स्वचालित रूप से अपडेट होता है", failedMsg: "प्रसंस्करण विफल" },
    auth: { loginTitle: "वापसी पर स्वागत है", loginSubtitle: "अपने TranCut खाते में साइन इन करें", signupTitle: "अपना खाता बनाएं", signupSubtitle: "मुफ़्त — 5 वीडियो/माह, प्रत्येक 2 मिनट तक", email: "ईमेल", password: "पासवर्ड", passwordHint: "न्यूनतम 8 अक्षर", signingIn: "साइन इन हो रहा है…", signIn: "साइन इन", creating: "खाता बनाया जा रहा है…", createAccount: "खाता बनाएं", noAccount: "खाता नहीं है?", signUpFree: "मुफ़्त पंजीकरण", haveAccount: "पहले से खाता है?" },
    footer: "TranCut · trancut.com",
  },

  it: {
    nav: { login: "Accedi", getStarted: "Inizia gratuitamente", upload: "Carica", history: "Cronologia", signOut: "Esci" },
    hero: { badge: "57 lingue · Doppiaggio IA · Sottotitoli incorporati", title1: "Traduci i tuoi video.", title2: "Senza sforzo.", subtitle: "Carica un video, scegli le lingue e ottieni sottotitoli, doppiaggio e didascalie incorporate in pochi minuti. Supporta 57 lingue.", ctaPrimary: "Inizia gratuitamente", ctaSecondary: "Accedi", freeNote: "Gratis: fino a 2 min · Senza carta di credito" },
    features: { title: "", items: [{ title: "Trascrizione in 57 lingue", description: "Powered by Whisper AI — rileva automaticamente la lingua, gestisce accenti, parlato veloce e rumore di fondo." }, { title: "Doppiaggio e sottotitoli IA", description: "Scegli tra 6 voci per il doppiaggio, incorpora sottotitoli (sorgente, destinazione o bilingue) direttamente nel video." }, { title: "Formati di output flessibili", description: "Scarica file SRT, video con sottotitoli incorporati o MP4 doppiato con IA — pronto per qualsiasi piattaforma." }] },
    pricing: { title: "Prezzi semplici", subtitle: "Inizia gratuitamente, aggiorna quando ne hai bisogno.", free: { tier: "Gratuito", price: "$0", features: ["Fino a 2 min / video", "5 video / mese", "SRT bilingue"] }, pro: { tier: "Pro", price: "Prossimamente", features: ["Fino a 20 min / video", "Video illimitati", "Elaborazione prioritaria"] } },
    upload: { title: "Nuova trascrizione", subtitle: "Carica un video per ottenere i sottotitoli.", dropTitle: "Trascina il tuo video qui", dropSubtitle: "o clicca per sfogliare · MP4, MOV, M4V", dropNote: "Piano gratuito: fino a 2 min", checking: "Verifica", uploading: "Caricamento…", queued: "Lavoro in coda — reindirizzamento…", errorType: "Sono supportati solo i file MP4, MOV o M4V.", errorDuration: (dur: number, max: number) => `Il video dura ${dur}s — il piano gratuito supporta fino a ${max}s (2 min).` },
    jobs: { title: "Cronologia", newVideo: "Nuovo video", empty: "Nessun lavoro", emptyLink: "Carica il tuo primo video →", loading: "Caricamento…", status: { pending: "in attesa", processing: "in elaborazione", completed: "completato", failed: "fallito" } },
    jobDetail: { allJobs: "Tutti i lavori", loading: "Caricamento…", ready: "I tuoi file di sottotitoli sono pronti:", bilingual: "SRT bilingue", bilingualDesc: "Ideale per la pubblicazione — entrambe le lingue sovrapposte", englishOnly: "Solo SRT inglese", englishOnlyDesc: "Trascrizione originale", pendingMsg: "In attesa nella coda…", processingMsg: "Trascrizione e traduzione…", pollingNote: "Questa pagina si aggiorna automaticamente", failedMsg: "Elaborazione fallita" },
    auth: { loginTitle: "Bentornato", loginSubtitle: "Accedi al tuo account TranCut", signupTitle: "Crea il tuo account", signupSubtitle: "Gratis — 5 video/mese, fino a 2 min ciascuno", email: "Email", password: "Password", passwordHint: "Minimo 8 caratteri", signingIn: "Accesso…", signIn: "Accedi", creating: "Creazione account…", createAccount: "Crea account", noAccount: "Non hai un account?", signUpFree: "Registrati gratuitamente", haveAccount: "Hai già un account?" },
    footer: "TranCut · trancut.com",
  },

  nl: {
    nav: { login: "Inloggen", getStarted: "Gratis beginnen", upload: "Uploaden", history: "Geschiedenis", signOut: "Uitloggen" },
    hero: { badge: "57 talen · AI-nasynchronisatie · Ingebakken ondertitels", title1: "Vertaal je video's.", title2: "Moeiteloos.", subtitle: "Upload een video, kies je talen en krijg ondertitels, nasynchronisatie en ingebakken bijschriften — in minuten. Ondersteunt 57 talen.", ctaPrimary: "Gratis beginnen", ctaSecondary: "Inloggen", freeNote: "Gratis: tot 2 min · Geen creditcard vereist" },
    features: { title: "", items: [{ title: "Transcriptie in 57 talen", description: "Aangedreven door Whisper AI — detecteert taal automatisch, verwerkt accenten, snel spraak en achtergrondgeluid." }, { title: "AI-nasynchronisatie en ondertitels", description: "Kies uit 6 stemmen voor nasynchronisatie, brand ondertitels (bron, doel of tweetalig) direct in je video." }, { title: "Flexibele uitvoerformaten", description: "Download SRT-bestanden, video met ingebakken ondertitels of AI-nagesynchroniseerde MP4 — klaar voor elk platform." }] },
    pricing: { title: "Eenvoudige prijzen", subtitle: "Begin gratis, upgrade wanneer je meer nodig hebt.", free: { tier: "Gratis", price: "$0", features: ["Tot 2 min / video", "5 video's / maand", "Tweetalige SRT"] }, pro: { tier: "Pro", price: "Binnenkort", features: ["Tot 20 min / video", "Onbeperkte video's", "Prioriteitsverwerking"] } },
    upload: { title: "Nieuwe transcriptie", subtitle: "Upload een video om ondertitels te krijgen.", dropTitle: "Zet je video hier neer", dropSubtitle: "of klik om te bladeren · MP4, MOV, M4V", dropNote: "Gratis plan: tot 2 min", checking: "Controleren", uploading: "Uploaden…", queued: "Taak in wachtrij — omleiden…", errorType: "Alleen MP4-, MOV- of M4V-bestanden worden ondersteund.", errorDuration: (dur: number, max: number) => `Video is ${dur}s — gratis plan ondersteunt tot ${max}s (2 min).` },
    jobs: { title: "Geschiedenis", newVideo: "Nieuwe video", empty: "Geen taken", emptyLink: "Upload je eerste video →", loading: "Laden…", status: { pending: "in behandeling", processing: "verwerken", completed: "voltooid", failed: "mislukt" } },
    jobDetail: { allJobs: "Alle taken", loading: "Laden…", ready: "Je ondertitelbestanden zijn klaar:", bilingual: "Tweetalige SRT", bilingualDesc: "Beste voor publiceren — beide talen gestapeld", englishOnly: "Alleen Engelse SRT", englishOnlyDesc: "Originele transcriptie", pendingMsg: "Wachten in wachtrij…", processingMsg: "Transcriberen en vertalen…", pollingNote: "Deze pagina wordt automatisch bijgewerkt", failedMsg: "Verwerking mislukt" },
    auth: { loginTitle: "Welkom terug", loginSubtitle: "Log in op je TranCut-account", signupTitle: "Maak je account aan", signupSubtitle: "Gratis — 5 video's/maand, tot 2 min elk", email: "E-mail", password: "Wachtwoord", passwordHint: "Minimaal 8 tekens", signingIn: "Inloggen…", signIn: "Inloggen", creating: "Account aanmaken…", createAccount: "Account aanmaken", noAccount: "Geen account?", signUpFree: "Gratis registreren", haveAccount: "Al een account?" },
    footer: "TranCut · trancut.com",
  },

  tr: {
    nav: { login: "Giriş yap", getStarted: "Ücretsiz başla", upload: "Yükle", history: "Geçmiş", signOut: "Çıkış yap" },
    hero: { badge: "57 dil · Yapay zeka dublajı · Yerleşik altyazı", title1: "Videolarını çevir.", title2: "Zahmetsizce.", subtitle: "Bir video yükle, dillerini seç, dakikalar içinde altyazı, dublaj ve yerleşik altyazı al. 57 dil destekler.", ctaPrimary: "Ücretsiz başla", ctaSecondary: "Giriş yap", freeNote: "Ücretsiz: 2 dakikaya kadar · Kredi kartı gerekmez" },
    features: { title: "", items: [{ title: "57 dilde transkripsiyon", description: "Whisper AI tarafından güçlendirildi — dili otomatik algılar, aksanları, hızlı konuşmayı ve arka plan gürültüsünü işler." }, { title: "Yapay zeka dublajı ve altyazı", description: "Dublaj için 6 ses arasından seç, altyazıları (kaynak, hedef veya ikidilli) doğrudan videoya göm." }, { title: "Esnek çıktı formatları", description: "SRT dosyaları, yerleşik altyazılı video veya yapay zeka dublajlı MP4 indir — her platform için hazır." }] },
    pricing: { title: "Basit fiyatlandırma", subtitle: "Ücretsiz başla, daha fazlasına ihtiyaç duyduğunda yükselt.", free: { tier: "Ücretsiz", price: "$0", features: ["2 dakikaya kadar / video", "5 video / ay", "İkidilli SRT"] }, pro: { tier: "Pro", price: "Yakında", features: ["20 dakikaya kadar / video", "Sınırsız video", "Öncelikli işlem"] } },
    upload: { title: "Yeni transkripsiyon", subtitle: "Altyazı almak için bir video yükle.", dropTitle: "Videonuzu buraya bırakın", dropSubtitle: "veya göz atmak için tıklayın · MP4, MOV, M4V", dropNote: "Ücretsiz plan: 2 dakikaya kadar", checking: "Kontrol ediliyor", uploading: "Yükleniyor…", queued: "İş kuyruğa alındı — yönlendiriliyor…", errorType: "Yalnızca MP4, MOV veya M4V dosyaları desteklenir.", errorDuration: (dur: number, max: number) => `Video ${dur}s — ücretsiz plan en fazla ${max}s (2 dak) destekler.` },
    jobs: { title: "Geçmiş", newVideo: "Yeni video", empty: "Henüz iş yok", emptyLink: "İlk videonuzu yükleyin →", loading: "Yükleniyor…", status: { pending: "beklemede", processing: "işleniyor", completed: "tamamlandı", failed: "başarısız" } },
    jobDetail: { allJobs: "Tüm işler", loading: "Yükleniyor…", ready: "Altyazı dosyalarınız hazır:", bilingual: "İkidilli SRT", bilingualDesc: "Yayınlamak için en iyi — her iki dil üst üste", englishOnly: "Yalnızca İngilizce SRT", englishOnlyDesc: "Orijinal transkripsiyon", pendingMsg: "Kuyrukta bekleniyor…", processingMsg: "Transkripsiyon ve çeviri yapılıyor…", pollingNote: "Bu sayfa otomatik olarak güncellenir", failedMsg: "İşlem başarısız" },
    auth: { loginTitle: "Tekrar hoş geldiniz", loginSubtitle: "TranCut hesabınıza giriş yapın", signupTitle: "Hesabınızı oluşturun", signupSubtitle: "Ücretsiz — ayda 5 video, her biri en fazla 2 dak", email: "E-posta", password: "Şifre", passwordHint: "En az 8 karakter", signingIn: "Giriş yapılıyor…", signIn: "Giriş yap", creating: "Hesap oluşturuluyor…", createAccount: "Hesap oluştur", noAccount: "Hesabınız yok mu?", signUpFree: "Ücretsiz kaydol", haveAccount: "Zaten hesabınız var mı?" },
    footer: "TranCut · trancut.com",
  },

  vi: {
    nav: { login: "Đăng nhập", getStarted: "Bắt đầu miễn phí", upload: "Tải lên", history: "Lịch sử", signOut: "Đăng xuất" },
    hero: { badge: "57 ngôn ngữ · Lồng tiếng AI · Phụ đề nhúng", title1: "Dịch video của bạn.", title2: "Dễ dàng.", subtitle: "Tải lên video, chọn ngôn ngữ và nhận phụ đề, lồng tiếng và phụ đề nhúng trong vài phút. Hỗ trợ 57 ngôn ngữ.", ctaPrimary: "Bắt đầu miễn phí", ctaSecondary: "Đăng nhập", freeNote: "Miễn phí: tối đa 2 phút · Không cần thẻ tín dụng" },
    features: { title: "", items: [{ title: "Phiên âm 57 ngôn ngữ", description: "Powered by Whisper AI — tự động phát hiện ngôn ngữ, xử lý giọng địa phương, nói nhanh và tiếng ồn nền." }, { title: "Lồng tiếng và phụ đề AI", description: "Chọn từ 6 giọng để lồng tiếng, nhúng phụ đề (gốc, dịch hoặc song ngữ) trực tiếp vào video." }, { title: "Định dạng đầu ra linh hoạt", description: "Tải xuống file SRT, video có phụ đề nhúng hoặc MP4 lồng tiếng AI — sẵn sàng cho mọi nền tảng." }] },
    pricing: { title: "Giá đơn giản", subtitle: "Bắt đầu miễn phí, nâng cấp khi cần thêm.", free: { tier: "Miễn phí", price: "$0", features: ["Tối đa 2 phút / video", "5 video / tháng", "SRT song ngữ"] }, pro: { tier: "Pro", price: "Sắp ra mắt", features: ["Tối đa 20 phút / video", "Video không giới hạn", "Ưu tiên xử lý"] } },
    upload: { title: "Phiên âm mới", subtitle: "Tải lên video để nhận phụ đề.", dropTitle: "Thả video của bạn vào đây", dropSubtitle: "hoặc nhấp để duyệt · MP4, MOV, M4V", dropNote: "Gói miễn phí: tối đa 2 phút", checking: "Đang kiểm tra", uploading: "Đang tải lên…", queued: "Công việc đã vào hàng đợi — đang chuyển hướng…", errorType: "Chỉ hỗ trợ file MP4, MOV hoặc M4V.", errorDuration: (dur: number, max: number) => `Video dài ${dur}s — gói miễn phí hỗ trợ tối đa ${max}s (2 phút).` },
    jobs: { title: "Lịch sử", newVideo: "Video mới", empty: "Chưa có công việc", emptyLink: "Tải lên video đầu tiên →", loading: "Đang tải…", status: { pending: "đang chờ", processing: "đang xử lý", completed: "hoàn thành", failed: "thất bại" } },
    jobDetail: { allJobs: "Tất cả công việc", loading: "Đang tải…", ready: "File phụ đề của bạn đã sẵn sàng:", bilingual: "SRT song ngữ", bilingualDesc: "Tốt nhất để xuất bản — cả hai ngôn ngữ xếp chồng", englishOnly: "Chỉ SRT tiếng Anh", englishOnlyDesc: "Phiên âm gốc", pendingMsg: "Đang chờ trong hàng đợi…", processingMsg: "Đang phiên âm và dịch…", pollingNote: "Trang này tự động cập nhật", failedMsg: "Xử lý thất bại" },
    auth: { loginTitle: "Chào mừng trở lại", loginSubtitle: "Đăng nhập vào tài khoản TranCut", signupTitle: "Tạo tài khoản", signupSubtitle: "Miễn phí — 5 video/tháng, tối đa 2 phút mỗi video", email: "Email", password: "Mật khẩu", passwordHint: "Tối thiểu 8 ký tự", signingIn: "Đang đăng nhập…", signIn: "Đăng nhập", creating: "Đang tạo tài khoản…", createAccount: "Tạo tài khoản", noAccount: "Chưa có tài khoản?", signUpFree: "Đăng ký miễn phí", haveAccount: "Đã có tài khoản?" },
    footer: "TranCut · trancut.com",
  },

  th: {
    nav: { login: "เข้าสู่ระบบ", getStarted: "เริ่มต้นฟรี", upload: "อัปโหลด", history: "ประวัติ", signOut: "ออกจากระบบ" },
    hero: { badge: "57 ภาษา · การพากย์ AI · คำบรรยายฝังอยู่", title1: "แปลวิดีโอของคุณ", title2: "อย่างง่ายดาย", subtitle: "อัปโหลดวิดีโอ เลือกภาษา และรับคำบรรยาย การพากย์เสียง และคำบรรยายที่ฝังไว้ในไม่กี่นาที รองรับ 57 ภาษา", ctaPrimary: "เริ่มต้นฟรี", ctaSecondary: "เข้าสู่ระบบ", freeNote: "ฟรี: สูงสุด 2 นาที · ไม่ต้องใช้บัตรเครดิต" },
    features: { title: "", items: [{ title: "การถอดความ 57 ภาษา", description: "ขับเคลื่อนโดย Whisper AI — ตรวจจับภาษาโดยอัตโนมัติ จัดการสำเนียง การพูดเร็ว และเสียงรบกวน" }, { title: "การพากย์เสียงและคำบรรยาย AI", description: "เลือกจาก 6 เสียงสำหรับการพากย์ เบิร์นคำบรรยาย (ต้นฉบับ แปล หรือสองภาษา) ลงในวิดีโอโดยตรง" }, { title: "รูปแบบเอาต์พุตที่ยืดหยุ่น", description: "ดาวน์โหลดไฟล์ SRT วิดีโอที่มีคำบรรยายฝัง หรือ MP4 พากย์เสียง AI — พร้อมสำหรับทุกแพลตฟอร์ม" }] },
    pricing: { title: "ราคาที่เรียบง่าย", subtitle: "เริ่มต้นฟรี อัปเกรดเมื่อต้องการมากขึ้น", free: { tier: "ฟรี", price: "$0", features: ["สูงสุด 2 นาที / วิดีโอ", "5 วิดีโอ / เดือน", "SRT สองภาษา"] }, pro: { tier: "โปร", price: "เร็วๆ นี้", features: ["สูงสุด 20 นาที / วิดีโอ", "วิดีโอไม่จำกัด", "ประมวลผลแบบให้ความสำคัญ"] } },
    upload: { title: "การถอดความใหม่", subtitle: "อัปโหลดวิดีโอเพื่อรับคำบรรยาย", dropTitle: "วางวิดีโอของคุณที่นี่", dropSubtitle: "หรือคลิกเพื่อค้นหา · MP4, MOV, M4V", dropNote: "แผนฟรี: สูงสุด 2 นาที", checking: "กำลังตรวจสอบ", uploading: "กำลังอัปโหลด…", queued: "งานอยู่ในคิว — กำลังเปลี่ยนเส้นทาง…", errorType: "รองรับเฉพาะไฟล์ MP4, MOV หรือ M4V เท่านั้น", errorDuration: (dur: number, max: number) => `วิดีโอยาว ${dur} วินาที — แผนฟรีรองรับสูงสุด ${max} วินาที (2 นาที)` },
    jobs: { title: "ประวัติ", newVideo: "วิดีโอใหม่", empty: "ไม่มีงาน", emptyLink: "อัปโหลดวิดีโอแรกของคุณ →", loading: "กำลังโหลด…", status: { pending: "รอดำเนินการ", processing: "กำลังประมวลผล", completed: "เสร็จสิ้น", failed: "ล้มเหลว" } },
    jobDetail: { allJobs: "งานทั้งหมด", loading: "กำลังโหลด…", ready: "ไฟล์คำบรรยายของคุณพร้อมแล้ว:", bilingual: "SRT สองภาษา", bilingualDesc: "ดีที่สุดสำหรับการเผยแพร่ — ทั้งสองภาษาซ้อนกัน", englishOnly: "SRT ภาษาอังกฤษเท่านั้น", englishOnlyDesc: "การถอดความต้นฉบับ", pendingMsg: "รอในคิว…", processingMsg: "กำลังถอดความและแปล…", pollingNote: "หน้านี้อัปเดตโดยอัตโนมัติ", failedMsg: "การประมวลผลล้มเหลว" },
    auth: { loginTitle: "ยินดีต้อนรับกลับ", loginSubtitle: "เข้าสู่ระบบบัญชี TranCut ของคุณ", signupTitle: "สร้างบัญชีของคุณ", signupSubtitle: "ฟรี — 5 วิดีโอ/เดือน สูงสุด 2 นาทีต่อรายการ", email: "อีเมล", password: "รหัสผ่าน", passwordHint: "อย่างน้อย 8 ตัวอักษร", signingIn: "กำลังเข้าสู่ระบบ…", signIn: "เข้าสู่ระบบ", creating: "กำลังสร้างบัญชี…", createAccount: "สร้างบัญชี", noAccount: "ยังไม่มีบัญชี?", signUpFree: "สมัครฟรี", haveAccount: "มีบัญชีอยู่แล้ว?" },
    footer: "TranCut · trancut.com",
  },

  id: {
    nav: { login: "Masuk", getStarted: "Mulai gratis", upload: "Unggah", history: "Riwayat", signOut: "Keluar" },
    hero: { badge: "57 bahasa · Dubbing AI · Subtitle tertanam", title1: "Terjemahkan video Anda.", title2: "Dengan mudah.", subtitle: "Unggah video, pilih bahasa, dan dapatkan subtitle, dubbing, dan keterangan tertanam dalam hitungan menit. Mendukung 57 bahasa.", ctaPrimary: "Mulai gratis", ctaSecondary: "Masuk", freeNote: "Gratis: hingga 2 menit · Tidak perlu kartu kredit" },
    features: { title: "", items: [{ title: "Transkripsi dalam 57 bahasa", description: "Didukung oleh Whisper AI — mendeteksi bahasa secara otomatis, menangani aksen, ucapan cepat, dan kebisingan latar." }, { title: "Dubbing dan subtitle AI", description: "Pilih dari 6 suara untuk dubbing, bakar subtitle (sumber, target, atau bilingual) langsung ke video Anda." }, { title: "Format output fleksibel", description: "Unduh file SRT, video dengan subtitle tertanam, atau MP4 dengan dubbing AI — siap untuk platform apa pun." }] },
    pricing: { title: "Harga sederhana", subtitle: "Mulai gratis, tingkatkan ketika perlu lebih.", free: { tier: "Gratis", price: "$0", features: ["Hingga 2 menit / video", "5 video / bulan", "SRT bilingual"] }, pro: { tier: "Pro", price: "Segera hadir", features: ["Hingga 20 menit / video", "Video tak terbatas", "Pemrosesan prioritas"] } },
    upload: { title: "Transkripsi baru", subtitle: "Unggah video untuk mendapatkan subtitle.", dropTitle: "Seret video Anda ke sini", dropSubtitle: "atau klik untuk mencari · MP4, MOV, M4V", dropNote: "Paket gratis: hingga 2 menit", checking: "Memeriksa", uploading: "Mengunggah…", queued: "Pekerjaan dalam antrean — mengalihkan…", errorType: "Hanya file MP4, MOV, atau M4V yang didukung.", errorDuration: (dur: number, max: number) => `Video berdurasi ${dur}d — paket gratis mendukung hingga ${max}d (2 menit).` },
    jobs: { title: "Riwayat", newVideo: "Video baru", empty: "Belum ada pekerjaan", emptyLink: "Unggah video pertama Anda →", loading: "Memuat…", status: { pending: "menunggu", processing: "memproses", completed: "selesai", failed: "gagal" } },
    jobDetail: { allJobs: "Semua pekerjaan", loading: "Memuat…", ready: "File subtitle Anda sudah siap:", bilingual: "SRT bilingual", bilingualDesc: "Terbaik untuk diterbitkan — kedua bahasa ditumpuk", englishOnly: "SRT bahasa Inggris saja", englishOnlyDesc: "Transkripsi asli", pendingMsg: "Menunggu dalam antrean…", processingMsg: "Mentranskripsi dan menerjemahkan…", pollingNote: "Halaman ini diperbarui secara otomatis", failedMsg: "Pemrosesan gagal" },
    auth: { loginTitle: "Selamat datang kembali", loginSubtitle: "Masuk ke akun TranCut Anda", signupTitle: "Buat akun Anda", signupSubtitle: "Gratis — 5 video/bulan, hingga 2 menit masing-masing", email: "Email", password: "Kata sandi", passwordHint: "Minimum 8 karakter", signingIn: "Masuk…", signIn: "Masuk", creating: "Membuat akun…", createAccount: "Buat akun", noAccount: "Belum punya akun?", signUpFree: "Daftar gratis", haveAccount: "Sudah punya akun?" },
    footer: "TranCut · trancut.com",
  },

  pl: {
    nav: { login: "Zaloguj się", getStarted: "Zacznij za darmo", upload: "Prześlij", history: "Historia", signOut: "Wyloguj się" },
    hero: { badge: "57 języków · Dubbing AI · Napisy wbudowane", title1: "Tłumacz swoje filmy.", title2: "Bez wysiłku.", subtitle: "Prześlij film, wybierz języki i otrzymaj napisy, dubbing oraz napisy wbudowane w kilka minut. Obsługuje 57 języków.", ctaPrimary: "Zacznij za darmo", ctaSecondary: "Zaloguj się", freeNote: "Bezpłatnie: do 2 min · Bez karty kredytowej" },
    features: { title: "", items: [{ title: "Transkrypcja w 57 językach", description: "Oparte na Whisper AI — automatycznie wykrywa język, radzi sobie z akcentami, szybką mową i szumem w tle." }, { title: "Dubbing AI i napisy", description: "Wybierz spośród 6 głosów do dubbingu, wypal napisy (źródłowe, docelowe lub dwujęzyczne) bezpośrednio w filmie." }, { title: "Elastyczne formaty wyjściowe", description: "Pobierz pliki SRT, film z wbudowanymi napisami lub MP4 z dubbingiem AI — gotowe na każdą platformę." }] },
    pricing: { title: "Proste ceny", subtitle: "Zacznij za darmo, zaktualizuj gdy potrzebujesz więcej.", free: { tier: "Bezpłatny", price: "$0", features: ["Do 2 min / film", "5 filmów / miesiąc", "Dwujęzyczny SRT"] }, pro: { tier: "Pro", price: "Wkrótce", features: ["Do 20 min / film", "Nieograniczone filmy", "Priorytetowe przetwarzanie"] } },
    upload: { title: "Nowa transkrypcja", subtitle: "Prześlij film, aby uzyskać napisy.", dropTitle: "Upuść swój film tutaj", dropSubtitle: "lub kliknij, aby przeglądać · MP4, MOV, M4V", dropNote: "Plan bezpłatny: do 2 min", checking: "Sprawdzanie", uploading: "Przesyłanie…", queued: "Zadanie w kolejce — przekierowywanie…", errorType: "Obsługiwane są tylko pliki MP4, MOV lub M4V.", errorDuration: (dur: number, max: number) => `Film trwa ${dur}s — plan bezpłatny obsługuje do ${max}s (2 min).` },
    jobs: { title: "Historia", newVideo: "Nowy film", empty: "Brak zadań", emptyLink: "Prześlij swój pierwszy film →", loading: "Ładowanie…", status: { pending: "oczekujące", processing: "przetwarzanie", completed: "ukończone", failed: "nieudane" } },
    jobDetail: { allJobs: "Wszystkie zadania", loading: "Ładowanie…", ready: "Twoje pliki napisów są gotowe:", bilingual: "Dwujęzyczny SRT", bilingualDesc: "Najlepszy do publikacji — oba języki ułożone", englishOnly: "Tylko angielski SRT", englishOnlyDesc: "Oryginalna transkrypcja", pendingMsg: "Oczekiwanie w kolejce…", processingMsg: "Transkrypcja i tłumaczenie…", pollingNote: "Ta strona aktualizuje się automatycznie", failedMsg: "Przetwarzanie nie powiodło się" },
    auth: { loginTitle: "Witamy ponownie", loginSubtitle: "Zaloguj się do swojego konta TranCut", signupTitle: "Utwórz konto", signupSubtitle: "Bezpłatnie — 5 filmów/miesiąc, do 2 min każdy", email: "Email", password: "Hasło", passwordHint: "Minimum 8 znaków", signingIn: "Logowanie…", signIn: "Zaloguj się", creating: "Tworzenie konta…", createAccount: "Utwórz konto", noAccount: "Nie masz konta?", signUpFree: "Zarejestruj się za darmo", haveAccount: "Masz już konto?" },
    footer: "TranCut · trancut.com",
  },
} as const;

export type Translations = typeof translations[Locale];

// Upload zone UI strings — separate from the main translations object
// so upload-zone.tsx can look them up without touching the rest of i18n.
export const uploadZoneTranslations: Record<Locale, {
  sourceLang: string; targetLang: string; style: string; subtitle: string; voice: string; autoDetect: string;
  subtitleModes: { label: string; desc: string }[];
  voices: { label: string; desc: string }[];
  styles: { label: string; desc: string }[];
  expandPct: string; trimPct: string;
  dropTitle: string; dropSubtitle: string; dropNote: string; rewritePlaceholder: string;
}> = {
  en: {
    sourceLang: "Video language", targetLang: "Translation language", style: "Narration style", subtitle: "Subtitle output", voice: "Dubbing voice", autoDetect: "Auto detect",
    dropTitle: "Drop your video here", dropSubtitle: "or click to browse · MP4, MOV, M4V", dropNote: "Free plan: up to 2 min · Pro: up to 20 min", rewritePlaceholder: "Describe what you'd like to rewrite (optional)…",
    subtitleModes: [{ label: "No subtitles", desc: "SRT file only" }, { label: "Source subtitles", desc: "Burn source language" }, { label: "Target subtitles", desc: "Burn translated language" }],
    voices: [{ label: "No dubbing", desc: "Subtitle file only" }, { label: "Warm female", desc: "Gentle, good for tutorials" }, { label: "Deep male", desc: "Powerful, good for narration" }, { label: "Natural neutral", desc: "Balanced, general use" }, { label: "Clear lecture", desc: "Clear, good for courses" }, { label: "Story narrator", desc: "Warm, good for documentaries" }, { label: "Premium quality", desc: "Refined, brand videos" }],
    styles: [{ label: "Direct translation", desc: "Keep original, no rewrite" }, { label: "Documentary", desc: "Info-dense, engaging storytelling" }, { label: "Short-form social", desc: "Lively, for younger audiences" }, { label: "Concise", desc: "Keep core, trim length" }, { label: "Vivid colloquial", desc: "Expand content, casual tone" }],
    expandPct: "Expansion", trimPct: "Trim",
  },
  "zh-TW": {
    sourceLang: "影片語言", targetLang: "翻譯語言", style: "旁白風格", subtitle: "字幕輸出", voice: "配音聲音", autoDetect: "自動偵測",
    dropTitle: "將影片拖曳至此", dropSubtitle: "或點擊瀏覽 · MP4、MOV、M4V", dropNote: "免費版：最長 2 分鐘 · 專業版：最長 20 分鐘", rewritePlaceholder: "描述你想要改寫的內容（可選）…",
    subtitleModes: [{ label: "無字幕", desc: "僅輸出 SRT 檔" }, { label: "原文字幕", desc: "原始語言烙印" }, { label: "譯文字幕", desc: "翻譯語言烙印" }],
    voices: [{ label: "無配音", desc: "僅輸出字幕檔" }, { label: "溫和女聲", desc: "親切柔和，適合教程" }, { label: "穩重男聲", desc: "深沉有力，適合解說" }, { label: "自然中性", desc: "均衡自然，通用場景" }, { label: "清晰講解", desc: "清晰明快，適合課程" }, { label: "故事旁白", desc: "溫暖敘述，適合紀錄片" }, { label: "高級質感", desc: "精緻細膩，品牌影片" }],
    styles: [{ label: "直接翻譯", desc: "保留原始翻譯，不加工" }, { label: "紀錄片旁白", desc: "信息密度高，敘述通俗引人" }, { label: "社群短影音", desc: "活潑年輕，吸引新世代受眾" }, { label: "精簡版", desc: "留存核心，精幹簡短" }, { label: "生動口語", desc: "擴展內容，通俗解說" }],
    expandPct: "擴充幅度", trimPct: "精簡幅度",
  },
  "zh-CN": {
    sourceLang: "视频语言", targetLang: "翻译语言", style: "旁白风格", subtitle: "字幕输出", voice: "配音声音", autoDetect: "自动检测",
    dropTitle: "将视频拖拽至此", dropSubtitle: "或点击浏览 · MP4、MOV、M4V", dropNote: "免费版：最长 2 分钟 · 专业版：最长 20 分钟", rewritePlaceholder: "描述你想要改写的内容（可选）…",
    subtitleModes: [{ label: "无字幕", desc: "仅输出 SRT 文件" }, { label: "原文字幕", desc: "原始语言烙印" }, { label: "译文字幕", desc: "翻译语言烙印" }],
    voices: [{ label: "无配音", desc: "仅输出字幕文件" }, { label: "温和女声", desc: "亲切柔和，适合教程" }, { label: "稳重男声", desc: "深沉有力，适合解说" }, { label: "自然中性", desc: "均衡自然，通用场景" }, { label: "清晰讲解", desc: "清晰明快，适合课程" }, { label: "故事旁白", desc: "温暖叙述，适合纪录片" }, { label: "高级质感", desc: "精致细腻，品牌视频" }],
    styles: [{ label: "直接翻译", desc: "保留原始翻译，不加工" }, { label: "纪录片旁白", desc: "信息密度高，叙述通俗引人" }, { label: "社群短视频", desc: "活泼年轻，吸引新世代受众" }, { label: "精简版", desc: "留存核心，精干简短" }, { label: "生动口语", desc: "扩展内容，通俗解说" }],
    expandPct: "扩充幅度", trimPct: "精简幅度",
  },
  ja: {
    sourceLang: "動画の言語", targetLang: "翻訳言語", style: "ナレーションスタイル", subtitle: "字幕出力", voice: "吹き替え音声", autoDetect: "自動検出",
    dropTitle: "ここに動画をドロップ", dropSubtitle: "またはクリックして参照 · MP4、MOV、M4V", dropNote: "無料プラン：最大2分 · Proプラン：最大20分", rewritePlaceholder: "書き直したい内容を説明してください（任意）…",
    subtitleModes: [{ label: "字幕なし", desc: "SRTファイルのみ" }, { label: "原文字幕", desc: "元言語を焼き込み" }, { label: "訳文字幕", desc: "翻訳語を焼き込み" }],
    voices: [{ label: "吹き替えなし", desc: "字幕ファイルのみ" }, { label: "温かい女声", desc: "穏やか、チュートリアル向き" }, { label: "重厚な男声", desc: "力強い、解説向き" }, { label: "自然なニュートラル", desc: "バランス型、汎用" }, { label: "明瞭な解説", desc: "クリア、講座向き" }, { label: "ストーリーナレーター", desc: "温かみ、ドキュメンタリー向き" }, { label: "プレミアム品質", desc: "洗練、ブランド動画" }],
    styles: [{ label: "直訳", desc: "原訳をそのまま維持" }, { label: "ドキュメンタリー", desc: "情報密度高、引き込む語り" }, { label: "ショートSNS", desc: "活発、若い世代向け" }, { label: "簡潔版", desc: "核心を残し短縮" }, { label: "生き生きした口語", desc: "内容を展開、カジュアルなトーン" }],
    expandPct: "拡張量", trimPct: "短縮量",
  },
  ko: {
    sourceLang: "영상 언어", targetLang: "번역 언어", style: "내레이션 스타일", subtitle: "자막 출력", voice: "더빙 음성", autoDetect: "자동 감지",
    dropTitle: "여기에 영상을 드롭하세요", dropSubtitle: "또는 클릭하여 찾아보기 · MP4, MOV, M4V", dropNote: "무료 플랜: 최대 2분 · Pro 플랜: 최대 20분", rewritePlaceholder: "다시 작성하고 싶은 내용을 설명해 주세요 (선택사항)…",
    subtitleModes: [{ label: "자막 없음", desc: "SRT 파일만" }, { label: "원문 자막", desc: "원본 언어 삽입" }, { label: "번역 자막", desc: "번역 언어 삽입" }],
    voices: [{ label: "더빙 없음", desc: "자막 파일만" }, { label: "따뜻한 여성", desc: "부드러움, 튜토리얼에 적합" }, { label: "중후한 남성", desc: "강함, 해설에 적합" }, { label: "자연스러운 중성", desc: "균형적, 범용" }, { label: "명확한 강의", desc: "명료함, 강의에 적합" }, { label: "이야기 내레이터", desc: "따뜻함, 다큐멘터리에 적합" }, { label: "프리미엄 품질", desc: "세련됨, 브랜드 영상" }],
    styles: [{ label: "직역", desc: "원본 번역 유지" }, { label: "다큐멘터리", desc: "정보 밀도 높음, 몰입감 있는 이야기" }, { label: "숏폼 소셜", desc: "활기차고, 젊은 시청자용" }, { label: "간결 버전", desc: "핵심 유지, 길이 줄임" }, { label: "생생한 구어체", desc: "내용 확장, 캐주얼한 톤" }],
    expandPct: "확장량", trimPct: "축약량",
  },
  es: {
    sourceLang: "Idioma del video", targetLang: "Idioma de traducción", style: "Estilo de narración", subtitle: "Salida de subtítulos", voice: "Voz de doblaje", autoDetect: "Detectar automáticamente",
    dropTitle: "Suelta tu video aquí", dropSubtitle: "o haz clic para buscar · MP4, MOV, M4V", dropNote: "Plan gratuito: hasta 2 min · Pro: hasta 20 min", rewritePlaceholder: "Describe qué quieres reescribir (opcional)…",
    subtitleModes: [{ label: "Sin subtítulos", desc: "Solo archivo SRT" }, { label: "Subtítulos originales", desc: "Quemar idioma fuente" }, { label: "Subtítulos traducidos", desc: "Quemar idioma destino" }],
    voices: [{ label: "Sin doblaje", desc: "Solo archivo de subtítulos" }, { label: "Femenina cálida", desc: "Suave, ideal para tutoriales" }, { label: "Masculina profunda", desc: "Potente, ideal para narración" }, { label: "Neutro natural", desc: "Equilibrado, uso general" }, { label: "Conferencia clara", desc: "Claro, ideal para cursos" }, { label: "Narrador de historias", desc: "Cálido, ideal para documentales" }, { label: "Calidad premium", desc: "Refinado, videos de marca" }],
    styles: [{ label: "Traducción directa", desc: "Mantener original sin cambios" }, { label: "Narración documental", desc: "Alta densidad, narrativa atractiva" }, { label: "Redes sociales cortas", desc: "Animado, para audiencias jóvenes" }, { label: "Conciso", desc: "Mantener lo esencial, reducir longitud" }, { label: "Coloquial vívido", desc: "Expandir contenido, tono casual" }],
    expandPct: "Expansión", trimPct: "Reducción",
  },
  fr: {
    sourceLang: "Langue de la vidéo", targetLang: "Langue de traduction", style: "Style de narration", subtitle: "Sortie de sous-titres", voice: "Voix de doublage", autoDetect: "Détection automatique",
    dropTitle: "Déposez votre vidéo ici", dropSubtitle: "ou cliquez pour parcourir · MP4, MOV, M4V", dropNote: "Plan gratuit : jusqu'à 2 min · Pro : jusqu'à 20 min", rewritePlaceholder: "Décrivez ce que vous souhaitez réécrire (facultatif)…",
    subtitleModes: [{ label: "Sans sous-titres", desc: "Fichier SRT uniquement" }, { label: "Sous-titres source", desc: "Graver la langue source" }, { label: "Sous-titres traduits", desc: "Graver la langue cible" }],
    voices: [{ label: "Sans doublage", desc: "Fichier de sous-titres uniquement" }, { label: "Féminine chaleureuse", desc: "Douce, idéale pour tutoriels" }, { label: "Masculine profonde", desc: "Puissante, idéale pour narration" }, { label: "Neutre naturelle", desc: "Équilibrée, usage général" }, { label: "Conférence claire", desc: "Claire, idéale pour cours" }, { label: "Narrateur d'histoires", desc: "Chaleureuse, idéale pour documentaires" }, { label: "Qualité premium", desc: "Raffinée, vidéos de marque" }],
    styles: [{ label: "Traduction directe", desc: "Conserver l'original sans modification" }, { label: "Narration documentaire", desc: "Dense en info, récit engageant" }, { label: "Réseaux sociaux courts", desc: "Animé, pour jeune public" }, { label: "Concis", desc: "Garder l'essentiel, réduire la longueur" }, { label: "Langage vivant", desc: "Développer le contenu, ton décontracté" }],
    expandPct: "Expansion", trimPct: "Réduction",
  },
  de: {
    sourceLang: "Videosprache", targetLang: "Übersetzungssprache", style: "Erzählstil", subtitle: "Untertitelausgabe", voice: "Synchronstimme", autoDetect: "Automatisch erkennen",
    dropTitle: "Video hier ablegen", dropSubtitle: "oder klicken zum Durchsuchen · MP4, MOV, M4V", dropNote: "Gratis-Plan: bis zu 2 Min. · Pro: bis zu 20 Min.", rewritePlaceholder: "Beschreibe, was du umschreiben möchtest (optional)…",
    subtitleModes: [{ label: "Keine Untertitel", desc: "Nur SRT-Datei" }, { label: "Originaluntertitel", desc: "Quellsprache einbrennen" }, { label: "Übersetzte Untertitel", desc: "Zielsprache einbrennen" }],
    voices: [{ label: "Keine Synchronisation", desc: "Nur Untertiteldatei" }, { label: "Warme Frauenstimme", desc: "Sanft, für Tutorials geeignet" }, { label: "Tiefe Männerstimme", desc: "Kraftvoll, für Erklärungen" }, { label: "Natürlich neutral", desc: "Ausgewogen, allgemeine Verwendung" }, { label: "Klare Vorlesung", desc: "Klar, für Kurse geeignet" }, { label: "Geschichtenerzähler", desc: "Warm, für Dokumentationen" }, { label: "Premium-Qualität", desc: "Verfeinert, Markenvideos" }],
    styles: [{ label: "Direkte Übersetzung", desc: "Original beibehalten" }, { label: "Dokumentarnarration", desc: "Informationsdicht, fesselnd" }, { label: "Kurzform Social", desc: "Lebhaft, für jüngeres Publikum" }, { label: "Prägnant", desc: "Kern behalten, kürzen" }, { label: "Lebhafte Umgangssprache", desc: "Inhalt erweitern, lockerer Ton" }],
    expandPct: "Erweiterung", trimPct: "Kürzung",
  },
  pt: {
    sourceLang: "Idioma do vídeo", targetLang: "Idioma de tradução", style: "Estilo de narração", subtitle: "Saída de legendas", voice: "Voz de dublagem", autoDetect: "Detectar automaticamente",
    dropTitle: "Solte seu vídeo aqui", dropSubtitle: "ou clique para procurar · MP4, MOV, M4V", dropNote: "Plano gratuito: até 2 min · Pro: até 20 min", rewritePlaceholder: "Descreva o que deseja reescrever (opcional)…",
    subtitleModes: [{ label: "Sem legendas", desc: "Apenas arquivo SRT" }, { label: "Legendas originais", desc: "Gravar idioma fonte" }, { label: "Legendas traduzidas", desc: "Gravar idioma alvo" }],
    voices: [{ label: "Sem dublagem", desc: "Apenas arquivo de legendas" }, { label: "Voz feminina calorosa", desc: "Suave, ideal para tutoriais" }, { label: "Voz masculina profunda", desc: "Poderosa, ideal para narração" }, { label: "Neutro natural", desc: "Equilibrado, uso geral" }, { label: "Palestra clara", desc: "Clara, ideal para cursos" }, { label: "Narrador de histórias", desc: "Caloroso, ideal para documentários" }, { label: "Qualidade premium", desc: "Refinado, vídeos de marca" }],
    styles: [{ label: "Tradução direta", desc: "Manter original sem alterações" }, { label: "Narração documental", desc: "Denso em informação, narrativa envolvente" }, { label: "Mídia social curta", desc: "Animado, para público jovem" }, { label: "Conciso", desc: "Manter o essencial, reduzir comprimento" }, { label: "Coloquial vívido", desc: "Expandir conteúdo, tom casual" }],
    expandPct: "Expansão", trimPct: "Redução",
  },
  ar: {
    sourceLang: "لغة الفيديو", targetLang: "لغة الترجمة", style: "أسلوب السرد", subtitle: "مخرجات الترجمة", voice: "صوت الدبلجة", autoDetect: "اكتشاف تلقائي",
    dropTitle: "أسقط الفيديو هنا", dropSubtitle: "أو انقر للتصفح · MP4، MOV، M4V", dropNote: "الخطة المجانية: حتى 2 دقيقة · Pro: حتى 20 دقيقة", rewritePlaceholder: "صف ما تريد إعادة كتابته (اختياري)…",
    subtitleModes: [{ label: "بدون ترجمة", desc: "ملف SRT فقط" }, { label: "ترجمة المصدر", desc: "تضمين اللغة الأصلية" }, { label: "الترجمة المستهدفة", desc: "تضمين اللغة المترجمة" }],
    voices: [{ label: "بدون دبلجة", desc: "ملف ترجمة فقط" }, { label: "صوت نسائي دافئ", desc: "ناعم، مناسب للدروس" }, { label: "صوت رجالي عميق", desc: "قوي، مناسب للشرح" }, { label: "محايد طبيعي", desc: "متوازن، استخدام عام" }, { label: "محاضرة واضحة", desc: "واضح، مناسب للدورات" }, { label: "راوي القصص", desc: "دافئ، مناسب للوثائقيات" }, { label: "جودة مميزة", desc: "راقٍ، لفيديوهات العلامات التجارية" }],
    styles: [{ label: "ترجمة مباشرة", desc: "الحفاظ على الأصل دون تعديل" }, { label: "سرد وثائقي", desc: "كثيف المعلومات، قصص جذابة" }, { label: "وسائل التواصل القصيرة", desc: "نشيط، للجمهور الشاب" }, { label: "موجز", desc: "الحفاظ على الجوهر، تقليل الطول" }, { label: "عامية حيوية", desc: "توسيع المحتوى، نبرة غير رسمية" }],
    expandPct: "نسبة التوسع", trimPct: "نسبة التقليص",
  },
  ru: {
    sourceLang: "Язык видео", targetLang: "Язык перевода", style: "Стиль повествования", subtitle: "Вывод субтитров", voice: "Голос дубляжа", autoDetect: "Автоопределение",
    dropTitle: "Перетащите видео сюда", dropSubtitle: "или нажмите для выбора · MP4, MOV, M4V", dropNote: "Бесплатный план: до 2 мин · Pro: до 20 мин", rewritePlaceholder: "Опишите, что хотите переписать (необязательно)…",
    subtitleModes: [{ label: "Без субтитров", desc: "Только файл SRT" }, { label: "Субтитры оригинала", desc: "Вжечь исходный язык" }, { label: "Субтитры перевода", desc: "Вжечь целевой язык" }],
    voices: [{ label: "Без дубляжа", desc: "Только файл субтитров" }, { label: "Тёплый женский", desc: "Мягкий, для обучающих видео" }, { label: "Глубокий мужской", desc: "Мощный, для повествования" }, { label: "Нейтральный", desc: "Сбалансированный, универсальный" }, { label: "Чёткая лекция", desc: "Ясный, для курсов" }, { label: "Рассказчик", desc: "Тёплый, для документальных фильмов" }, { label: "Премиум качество", desc: "Изысканный, для брендовых видео" }],
    styles: [{ label: "Прямой перевод", desc: "Сохранить оригинал без изменений" }, { label: "Документальное повествование", desc: "Насыщенно, увлекательный рассказ" }, { label: "Короткие соцсети", desc: "Живо, для молодой аудитории" }, { label: "Краткий", desc: "Сохранить суть, сократить длину" }, { label: "Живой разговорный", desc: "Расширить содержание, непринуждённый тон" }],
    expandPct: "Расширение", trimPct: "Сокращение",
  },
  hi: {
    sourceLang: "वीडियो की भाषा", targetLang: "अनुवाद भाषा", style: "कथन शैली", subtitle: "उपशीर्षक आउटपुट", voice: "डबिंग आवाज़", autoDetect: "स्वतः पहचानें",
    dropTitle: "यहाँ वीडियो छोड़ें", dropSubtitle: "या ब्राउज़ करने के लिए क्लिक करें · MP4, MOV, M4V", dropNote: "मुफ़्त प्लान: 2 मिनट तक · Pro: 20 मिनट तक", rewritePlaceholder: "आप क्या दोबारा लिखना चाहते हैं बताएं (वैकल्पिक)…",
    subtitleModes: [{ label: "कोई उपशीर्षक नहीं", desc: "केवल SRT फ़ाइल" }, { label: "मूल उपशीर्षक", desc: "स्रोत भाषा जलाएं" }, { label: "अनुवाद उपशीर्षक", desc: "लक्ष्य भाषा जलाएं" }],
    voices: [{ label: "कोई डबिंग नहीं", desc: "केवल उपशीर्षक फ़ाइल" }, { label: "गर्म महिला स्वर", desc: "मृदु, ट्यूटोरियल के लिए" }, { label: "गहरा पुरुष स्वर", desc: "शक्तिशाली, कथन के लिए" }, { label: "प्राकृतिक तटस्थ", desc: "संतुलित, सामान्य उपयोग" }, { label: "स्पष्ट व्याख्यान", desc: "स्पष्ट, पाठ्यक्रम के लिए" }, { label: "कहानी कथावाचक", desc: "गर्म, वृत्तचित्र के लिए" }, { label: "प्रीमियम गुणवत्ता", desc: "परिष्कृत, ब्रांड वीडियो" }],
    styles: [{ label: "सीधा अनुवाद", desc: "मूल को बिना बदलाव के रखें" }, { label: "वृत्तचित्र कथन", desc: "सूचना-घना, आकर्षक कहानी" }, { label: "सोशल शॉर्ट-फॉर्म", desc: "जीवंत, युवा दर्शकों के लिए" }, { label: "संक्षिप्त", desc: "मूल बनाए रखें, लंबाई कम करें" }, { label: "जीवंत बोलचाल", desc: "सामग्री विस्तार, आकस्मिक स्वर" }],
    expandPct: "विस्तार", trimPct: "संक्षिप्त",
  },
  it: {
    sourceLang: "Lingua del video", targetLang: "Lingua di traduzione", style: "Stile di narrazione", subtitle: "Output sottotitoli", voice: "Voce doppiaggio", autoDetect: "Rilevamento automatico",
    dropTitle: "Trascina il video qui", dropSubtitle: "o clicca per sfogliare · MP4, MOV, M4V", dropNote: "Piano gratuito: fino a 2 min · Pro: fino a 20 min", rewritePlaceholder: "Descrivi cosa vuoi riscrivere (facoltativo)…",
    subtitleModes: [{ label: "Senza sottotitoli", desc: "Solo file SRT" }, { label: "Sottotitoli originali", desc: "Incorpora lingua sorgente" }, { label: "Sottotitoli tradotti", desc: "Incorpora lingua target" }],
    voices: [{ label: "Senza doppiaggio", desc: "Solo file sottotitoli" }, { label: "Femminile caldo", desc: "Morbido, per tutorial" }, { label: "Maschile profondo", desc: "Potente, per narrazione" }, { label: "Neutro naturale", desc: "Equilibrato, uso generale" }, { label: "Lezione chiara", desc: "Chiaro, per corsi" }, { label: "Narratore di storie", desc: "Caldo, per documentari" }, { label: "Qualità premium", desc: "Raffinato, video di marca" }],
    styles: [{ label: "Traduzione diretta", desc: "Mantieni originale senza modifiche" }, { label: "Narrazione documentaria", desc: "Ricco di info, narrativa coinvolgente" }, { label: "Social short-form", desc: "Vivace, per giovane pubblico" }, { label: "Conciso", desc: "Mantieni il nucleo, riduci la lunghezza" }, { label: "Colloquiale vivace", desc: "Espandi contenuto, tono casual" }],
    expandPct: "Espansione", trimPct: "Riduzione",
  },
  nl: {
    sourceLang: "Videotaal", targetLang: "Vertaaltaal", style: "Vertellerstijl", subtitle: "Ondertiteluitvoer", voice: "Nasynchronisatiestem", autoDetect: "Automatisch detecteren",
    dropTitle: "Sleep je video hier", dropSubtitle: "of klik om te bladeren · MP4, MOV, M4V", dropNote: "Gratis plan: tot 2 min · Pro: tot 20 min", rewritePlaceholder: "Beschrijf wat je wilt herschrijven (optioneel)…",
    subtitleModes: [{ label: "Geen ondertitels", desc: "Alleen SRT-bestand" }, { label: "Brontaalondertitels", desc: "Brontaal inbranden" }, { label: "Vertaalde ondertitels", desc: "Doeltaal inbranden" }],
    voices: [{ label: "Geen nasynchronisatie", desc: "Alleen ondertitelbestand" }, { label: "Warme vrouwenstem", desc: "Zacht, voor tutorials" }, { label: "Diepe mannenstem", desc: "Krachtig, voor vertelling" }, { label: "Natuurlijk neutraal", desc: "Gebalanceerd, algemeen gebruik" }, { label: "Duidelijk college", desc: "Helder, voor cursussen" }, { label: "Verhalenverteller", desc: "Warm, voor documentaires" }, { label: "Premiumkwaliteit", desc: "Verfijnd, merkvideos" }],
    styles: [{ label: "Directe vertaling", desc: "Origineel behouden zonder wijzigingen" }, { label: "Documentairevertellingen", desc: "Informatierijk, boeiend verhaal" }, { label: "Social short-form", desc: "Levendig, voor jong publiek" }, { label: "Beknopt", desc: "Kern behouden, lengte verminderen" }, { label: "Levendige spreektaal", desc: "Inhoud uitbreiden, informele toon" }],
    expandPct: "Uitbreiding", trimPct: "Inkorten",
  },
  tr: {
    sourceLang: "Video dili", targetLang: "Çeviri dili", style: "Anlatım stili", subtitle: "Altyazı çıktısı", voice: "Dublaj sesi", autoDetect: "Otomatik algıla",
    dropTitle: "Videonuzu buraya bırakın", dropSubtitle: "veya göz atmak için tıklayın · MP4, MOV, M4V", dropNote: "Ücretsiz plan: 2 dakikaya kadar · Pro: 20 dakikaya kadar", rewritePlaceholder: "Yeniden yazmak istediğinizi açıklayın (isteğe bağlı)…",
    subtitleModes: [{ label: "Altyazı yok", desc: "Yalnızca SRT dosyası" }, { label: "Kaynak altyazı", desc: "Kaynak dili yaz" }, { label: "Çeviri altyazısı", desc: "Hedef dili yaz" }],
    voices: [{ label: "Dublaj yok", desc: "Yalnızca altyazı dosyası" }, { label: "Sıcak kadın sesi", desc: "Yumuşak, eğitimler için" }, { label: "Derin erkek sesi", desc: "Güçlü, anlatım için" }, { label: "Doğal nötr", desc: "Dengeli, genel kullanım" }, { label: "Net ders anlatımı", desc: "Açık, kurslar için" }, { label: "Hikaye anlatıcısı", desc: "Sıcak, belgeseller için" }, { label: "Premium kalite", desc: "İnce, marka videoları" }],
    styles: [{ label: "Doğrudan çeviri", desc: "Orijinali değiştirmeden koruyun" }, { label: "Belgesel anlatımı", desc: "Bilgi yoğun, sürükleyici hikaye" }, { label: "Kısa sosyal medya", desc: "Canlı, genç kitle için" }, { label: "Kısa özet", desc: "Özü koruyun, uzunluğu azaltın" }, { label: "Canlı konuşma dili", desc: "İçeriği genişletin, rahat ton" }],
    expandPct: "Genişleme", trimPct: "Kısaltma",
  },
  vi: {
    sourceLang: "Ngôn ngữ video", targetLang: "Ngôn ngữ dịch", style: "Phong cách kể chuyện", subtitle: "Đầu ra phụ đề", voice: "Giọng lồng tiếng", autoDetect: "Tự động phát hiện",
    dropTitle: "Thả video vào đây", dropSubtitle: "hoặc nhấp để duyệt · MP4, MOV, M4V", dropNote: "Gói miễn phí: tối đa 2 phút · Pro: tối đa 20 phút", rewritePlaceholder: "Mô tả những gì bạn muốn viết lại (tùy chọn)…",
    subtitleModes: [{ label: "Không có phụ đề", desc: "Chỉ tệp SRT" }, { label: "Phụ đề gốc", desc: "Ghi ngôn ngữ nguồn" }, { label: "Phụ đề dịch", desc: "Ghi ngôn ngữ đích" }],
    voices: [{ label: "Không lồng tiếng", desc: "Chỉ tệp phụ đề" }, { label: "Giọng nữ ấm áp", desc: "Nhẹ nhàng, phù hợp hướng dẫn" }, { label: "Giọng nam trầm", desc: "Mạnh mẽ, phù hợp thuyết minh" }, { label: "Trung tính tự nhiên", desc: "Cân bằng, dùng chung" }, { label: "Giảng dạy rõ ràng", desc: "Rõ ràng, phù hợp khóa học" }, { label: "Người kể chuyện", desc: "Ấm áp, phù hợp tài liệu" }, { label: "Chất lượng cao cấp", desc: "Tinh tế, video thương hiệu" }],
    styles: [{ label: "Dịch trực tiếp", desc: "Giữ nguyên bản dịch gốc" }, { label: "Thuyết minh tài liệu", desc: "Thông tin dày, câu chuyện hấp dẫn" }, { label: "Mạng xã hội ngắn", desc: "Sôi động, cho khán giả trẻ" }, { label: "Súc tích", desc: "Giữ cốt lõi, giảm độ dài" }, { label: "Ngôn ngữ nói sinh động", desc: "Mở rộng nội dung, giọng thân mật" }],
    expandPct: "Mức mở rộng", trimPct: "Mức rút gọn",
  },
  th: {
    sourceLang: "ภาษาของวิดีโอ", targetLang: "ภาษาที่แปล", style: "สไตล์การบรรยาย", subtitle: "ผลลัพธ์คำบรรยาย", voice: "เสียงพากย์", autoDetect: "ตรวจจับอัตโนมัติ",
    dropTitle: "วางวิดีโอที่นี่", dropSubtitle: "หรือคลิกเพื่อเรียกดู · MP4, MOV, M4V", dropNote: "แผนฟรี: สูงสุด 2 นาที · Pro: สูงสุด 20 นาที", rewritePlaceholder: "อธิบายสิ่งที่ต้องการเขียนใหม่ (ไม่บังคับ)…",
    subtitleModes: [{ label: "ไม่มีคำบรรยาย", desc: "ไฟล์ SRT เท่านั้น" }, { label: "คำบรรยายต้นฉบับ", desc: "เผาภาษาต้นฉบับ" }, { label: "คำบรรยายแปล", desc: "เผาภาษาเป้าหมาย" }],
    voices: [{ label: "ไม่มีการพากย์", desc: "ไฟล์คำบรรยายเท่านั้น" }, { label: "เสียงหญิงอบอุ่น", desc: "นุ่มนวล เหมาะสำหรับบทเรียน" }, { label: "เสียงชายลึก", desc: "ทรงพลัง เหมาะสำหรับบรรยาย" }, { label: "กลางธรรมชาติ", desc: "สมดุล ใช้ทั่วไป" }, { label: "บรรยายชัดเจน", desc: "ชัดเจน เหมาะสำหรับคอร์ส" }, { label: "ผู้เล่าเรื่อง", desc: "อบอุ่น เหมาะสำหรับสารคดี" }, { label: "คุณภาพพรีเมียม", desc: "ประณีต วิดีโอแบรนด์" }],
    styles: [{ label: "แปลตรง", desc: "รักษาต้นฉบับโดยไม่เปลี่ยน" }, { label: "บรรยายสารคดี", desc: "ข้อมูลหนาแน่น เรื่องราวน่าสนใจ" }, { label: "โซเชียลมีเดียสั้น", desc: "มีชีวิตชีวา สำหรับผู้ชมรุ่นใหม่" }, { label: "กระชับ", desc: "รักษาแก่น ลดความยาว" }, { label: "ภาษาพูดที่สดใส", desc: "ขยายเนื้อหา โทนสบายๆ" }],
    expandPct: "ระดับการขยาย", trimPct: "ระดับการตัด",
  },
  id: {
    sourceLang: "Bahasa video", targetLang: "Bahasa terjemahan", style: "Gaya narasi", subtitle: "Output subtitle", voice: "Suara dubbing", autoDetect: "Deteksi otomatis",
    dropTitle: "Jatuhkan video Anda di sini", dropSubtitle: "atau klik untuk menelusuri · MP4, MOV, M4V", dropNote: "Paket gratis: hingga 2 menit · Pro: hingga 20 menit", rewritePlaceholder: "Jelaskan apa yang ingin Anda tulis ulang (opsional)…",
    subtitleModes: [{ label: "Tanpa subtitle", desc: "File SRT saja" }, { label: "Subtitle asli", desc: "Bakar bahasa sumber" }, { label: "Subtitle terjemahan", desc: "Bakar bahasa target" }],
    voices: [{ label: "Tanpa dubbing", desc: "File subtitle saja" }, { label: "Suara wanita hangat", desc: "Lembut, cocok untuk tutorial" }, { label: "Suara pria dalam", desc: "Kuat, cocok untuk narasi" }, { label: "Netral alami", desc: "Seimbang, penggunaan umum" }, { label: "Kuliah jelas", desc: "Jelas, cocok untuk kursus" }, { label: "Pencerita", desc: "Hangat, cocok untuk dokumenter" }, { label: "Kualitas premium", desc: "Halus, video merek" }],
    styles: [{ label: "Terjemahan langsung", desc: "Pertahankan asli tanpa perubahan" }, { label: "Narasi dokumenter", desc: "Padat info, cerita menarik" }, { label: "Media sosial pendek", desc: "Ceria, untuk penonton muda" }, { label: "Ringkas", desc: "Pertahankan inti, kurangi panjang" }, { label: "Bahasa sehari-hari hidup", desc: "Perluas konten, nada santai" }],
    expandPct: "Perluasan", trimPct: "Pengurangan",
  },
  pl: {
    sourceLang: "Język wideo", targetLang: "Język tłumaczenia", style: "Styl narracji", subtitle: "Wyjście napisów", voice: "Głos lektora", autoDetect: "Automatyczne wykrywanie",
    dropTitle: "Upuść wideo tutaj", dropSubtitle: "lub kliknij, aby przeglądać · MP4, MOV, M4V", dropNote: "Plan bezpłatny: do 2 min · Pro: do 20 min", rewritePlaceholder: "Opisz, co chcesz przepisać (opcjonalnie)…",
    subtitleModes: [{ label: "Bez napisów", desc: "Tylko plik SRT" }, { label: "Napisy oryginalne", desc: "Wypal język źródłowy" }, { label: "Napisy tłumaczone", desc: "Wypal język docelowy" }],
    voices: [{ label: "Bez lektora", desc: "Tylko plik napisów" }, { label: "Ciepły głos kobiecy", desc: "Łagodny, do tutoriali" }, { label: "Głęboki głos męski", desc: "Mocny, do narracji" }, { label: "Neutralny naturalny", desc: "Zrównoważony, ogólne użycie" }, { label: "Wyraźny wykład", desc: "Jasny, do kursów" }, { label: "Gawędziarz", desc: "Ciepły, do dokumentów" }, { label: "Jakość premium", desc: "Wyrafinowany, filmy markowe" }],
    styles: [{ label: "Tłumaczenie dosłowne", desc: "Zachowaj oryginał bez zmian" }, { label: "Narracja dokumentalna", desc: "Gęsta informacyjnie, wciągająca" }, { label: "Krótkie social media", desc: "Żywe, dla młodych odbiorców" }, { label: "Zwięzłe", desc: "Zachowaj sedno, skróć długość" }, { label: "Żywy potoczny", desc: "Rozszerz treść, swobodny ton" }],
    expandPct: "Rozszerzenie", trimPct: "Skrócenie",
  },
};
